### ISSUE TITLE
DragHandlers in MeasuringTape should use MoveableDragHandler

### ISSUE THREAD

**Issue by aaronsamuel137** [phetsims/scenery-phet#106]
During code review #68, @samreid and I noticed that the tape tip is not constrained to the drag bounds. 

Additionally, constraining the bounds in the way that it is currently done introduces a bug where the mouse position and the tape can get out of sync. Using MoveableDragHandler for both the tape and the tip will address these concerns.

**Comment by bereaphysics** [comment]
The current implementation of MeasuringTape (see https://github.com/phetsims/scenery-phet/commit/aa6e92ea021091d1f3fc0cb1e0d90ecc6dcd4982) uses two SimpleDragHandler. Although it is trivial to rewrite the tip drag Handler as a MovableDragHandler this is not so for the base drag handler. The base drag handler must have extra logic since it needs to know about the state of the tip (is it being dragged at the same time or not). It is not possible to write all that logic in the options for the   MovableDragHandler.  We would need a way to access to constrainLocation function inside MovableDragHandler.

**Comment by aaronsamuel137** [comment]
Because of some specialized behavior in MeasuringTape, I think it is best to leave the SimpleDragHandlers. I replaced constrainLocation with closestPointTo in MeasuringTape. Closing
