### ISSUE TITLE
MeasuringTape: options are not propagated to supertype

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#126]
The supertype constructor call is Node.call(this), and there's no call to this.mutate(options).  So it looks like options are not being propagated to the supertype. All common-code nodes need to handle this, so that standard scenery options (left, top, x, y, scale,...) can be specified in options.

**Comment by bereaphysics** [comment]
This issue is still relevant for the MeasuringTape (see https://github.com/phetsims/scenery-phet/commit/aa6e92ea021091d1f3fc0cb1e0d90ecc6dcd4982). 
Pickable, scaling, focusable are options that could be useful.  Therefore, it is worth to propagate options to the supertype. 

The main point of this issue is that it is possibly confusing since we don't want someone to use x and y positions to position the MeasuringTape. For this reason, clear documentation was added within the MeasuringTape about how to position the MeasuringTape.

**Comment by pixelzoom** [comment]
Assigning this to @aaronsamuel137 since he is assigned #106, which is also related to MeasuringTape.

**Comment by aaronsamuel137** [comment]
@bereaphysics and I decided that we should propogate to the supertype after all, and just add some documentation that the location should be set with basePositionProperty and tipPositionProperty.

Documentation added. Closing
