### ISSUE TITLE
Regression in MovableDragHandler

### ISSUE THREAD

**Issue by bereaphysics** [phetsims/scenery-phet#157]
In the commit https://github.com/phetsims/scenery-phet/commit/11d9a99b43f96e7ac723acde799ba23e1cf5eab8, there was a small change brought to the MovableDragHandler

for the start drag it used to be this, 
````
      // note where the drag started
      start: function( event ) {

        var messageIndex = arch && arch.start( 'user', self.togetherID, 'dragStarted', {
            positionX: locationProperty.get().x,
            positionY: locationProperty.get().y
          } );
        options.startDrag( event );
        var location = self._modelViewTransform.modelToViewPosition( locationProperty.get() );
        startOffset = event.currentTarget.globalToParentPoint( event.pointer.point ).minus( location );

        arch && arch.end( messageIndex );
      },
````

which was changed to this 
````
  start: function( event ) {

        var initialLocation = locationProperty.get();
        self.events.trigger1( 'startedCallbacksForDragStart', initialLocation );

        options.startDrag( event );

        var location = self._modelViewTransform.modelToViewPosition( initialLocation );
        startOffset = event.currentTarget.globalToParentPoint( event.pointer.point ).minus( location );

        self.events.trigger1( 'endedCallbacksForDragStart', initialLocation );
      },
````

If the options.startDrag(event) changes the locationProperty, then it doesn't affect the startOffset in the second scenario whereas it would in the first.

e.g .
````
 options.startDrag( event ){
  var globalPoint = chargedParticleNode.globalToParentPoint( event.pointer.point );
            // move this node upward so that the cursor touches the bottom of the chargedParticle
            locationProperty.set(modelViewTransform.viewToModelPosition( globalPoint.addXY( 0, -CIRCLE_RADIUS ) ));
````

This change introduced a regression in charges and fields. Not sure how many other simulations could be affected by this change.

**Comment by bereaphysics** [comment]
Assigning to @jbphet since he took over @samreid  responsabilities

**Comment by samreid** [comment]
Here is an implementation that seems like it addresses the symptom in charges and fields so that the particle appears centered above the pointer:

```js
      // note where the drag started
      start: function( event ) {

        var initialLocation = locationProperty.get();
        self.events.trigger1( 'startedCallbacksForDragStarted', initialLocation );

        options.startDrag( event );

        // Note the options.startDrag can change the locationProperty, so read it again above, see https://github.com/phetsims/scenery-phet/issues/157
        var location = self._modelViewTransform.modelToViewPosition( locationProperty.get() );
        startOffset = event.currentTarget.globalToParentPoint( event.pointer.point ).minus( location );

        self.events.trigger1( 'endedCallbacksForDragStarted', initialLocation );
      }
```

Can @bereaphysics @jbphet or @pixelzoom reviews this change before we commit it?  Also, visually inspecting the drag and end, it seems like they don't suffer the same fate, but it would be good for someone else to confirm that.

**Comment by pixelzoom** [comment]
Assigning to myself to review.

**Comment by bereaphysics** [comment]
As far as the behavior of MovableDragHandler goes, the proposed change would revert it to the how it used to work, which would fix the problem. I can' speak on how it affects the logging of events for together.js though.


Wouldn't want to have a parallel between the endDrag and the startDrag?
endDrag goes like this

````
      end: function( event ) {
        self.events.trigger1( 'startedCallbacksForDragEnded', locationProperty.get() );
        options.endDrag( event );
        self.events.trigger1( 'endedCallbacksForDragEnded', locationProperty.get() );
      }
````
so the startDrag could go like this.

```js
      // note where the drag started
      start: function( event ) {
        self.events.trigger1( 'startedCallbacksForDragStarted', locationProperty.get() );

        options.startDrag( event );

        // Note the options.startDrag can change the locationProperty, so read it again above, see https://github.com/phetsims/scenery-phet/issues/157
        var location = self._modelViewTransform.modelToViewPosition( locationProperty.get() );
        startOffset = event.currentTarget.globalToParentPoint( event.pointer.point ).minus( location );

        self.events.trigger1( 'endedCallbacksForDragStarted', locationProperty.get() );
      }
```

again i dont understand together.js so take my advice with a grain of salt, but it seems that endDrag and startDrag should behave in a similar way.

**Comment by samreid** [comment]
Ah yes, I think you are right about the options.XXXDrag() possibly changing the locationProperty in the drag and dragEnd cases as well, thanks @bereaphysics.

For the tandem/trigger messages, I think delivering the original message of the location of the object *before* the `options.startDrag` takes effect is desirable, and the location property change within the `options.startDrag` can be tracked by a property change notification if that property is tandemized.

**Comment by pixelzoom** [comment]
The fix to `start` looks good.  

I agree that a similar approach to reporting location should be used in `start` and `end` (and `drag`?), and that is currently not the case.  I'm not clear on which approach is desirable/required.  

Questions for @samreid:
• How do you want to proceed with this? Fix it as part of this issue? Open a new issue?  
• Which approach to use? 
• Which cases to fix? You mentioned "drag and dragEnd cases", which @bereaphysics did not mention.

**Comment by pixelzoom** [comment]
Labeling this as high-priority, since MovableDragHandler is used by many sims.

**Comment by samreid** [comment]
I think the proposed solution for start() is good.  end() is already OK since locationProperty.get() is called after the options.endDrag().  For drag() we just need to change its last line to:

self.events.trigger1( 'endedCallbacksForDragged', locationProperty.get() );

So I believe the entire SimpleDragHandler instantiation will be:

```js
    SimpleDragHandler.call( this, {

      allowTouchSnag: true,

      // note where the drag started
      start: function( event ) {

        self.events.trigger1( 'startedCallbacksForDragStarted', locationProperty.get() );

        options.startDrag( event );

        // Note the options.startDrag can change the locationProperty, so read it again above, see https://github.com/phetsims/scenery-phet/issues/157
        var location = self._modelViewTransform.modelToViewPosition( locationProperty.get() );
        startOffset = event.currentTarget.globalToParentPoint( event.pointer.point ).minus( location );

        self.events.trigger1( 'endedCallbacksForDragStarted', locationProperty.get() );
      },

      // change the location, adjust for starting offset, constrain to drag bounds
      drag: function( event ) {

        var parentPoint = event.currentTarget.globalToParentPoint( event.pointer.point ).minus( startOffset );
        var location = self._modelViewTransform.viewToModelPosition( parentPoint );
        location = constrainLocation( location, self._dragBounds );
        self.events.trigger1( 'startedCallbacksForDragged', location );

        locationProperty.set( location );

        options.onDrag( event );

        self.events.trigger1( 'endedCallbacksForDragged', locationProperty.get() );
      },

      end: function( event ) {
        self.events.trigger1( 'startedCallbacksForDragEnded', locationProperty.get() );
        options.endDrag( event );
        self.events.trigger1( 'endedCallbacksForDragEnded', locationProperty.get() );
      }
    } )
```

Can @pixelzoom review and commit if it looks correct?

Also, in response to the questions above:

> • How do you want to proceed with this? Fix it as part of this issue? Open a new issue?

This issue seems good.

> • Which approach to use? 

The above proposal seems good.

> • Which cases to fix? You mentioned "drag and dragEnd cases", which @bereaphysics did not mention.

I believe the fixes above will handle start/drag/end cases uniformly.

**Comment by pixelzoom** [comment]
Looks OK to me. But I'm not totally clear on what the requirements are for events (i.e., whether you want to send the value before or after modification).

**Comment by samreid** [comment]
I'm not totally clear what values would be best to send either.  Right now, it will be sending the location before the object is grabbed (which I think sounds best) and after it is grabbed (though I don't believe together.js is currently doing anything with the latter).  Also, we are sending the model property value, rather than the node coordinates.

If the object is at (x0,y0) before it is grabbed, then the locationProperty is changed by the options, that will be shown in the data stream as a nested child, so I suspect this will be sufficient.

**Comment by pixelzoom** [comment]
Sounds good.

Who is going to make the change proposed by @samreid in https://github.com/phetsims/scenery-phet/issues/157#issuecomment-101771817 ?

**Comment by pixelzoom** [comment]
Since @samreid and @bereaphysics are both gone for an extended period of time, I implemented the solution proposed in https://github.com/phetsims/scenery-phet/issues/157#issuecomment-101771817.  

I have no idea how this affects data collection, so assigning to @jbphet to verify that (a) this doesn't cause problems with data collection, and (b) this is what is desired for data collection.

**Comment by samreid** [comment]
One issue that confused me when trying to test these changes was the difference in drag behavior when dragging something out of the toolbox vs dragging in the play area.  I documented the difference here: https://github.com/phetsims/charges-and-fields/issues/31

**Comment by jbphet** [comment]
I've tested the behavior on the instrumented versions of concentration and faradays-law.  It seems fine, at least for the current round of data collection.  The commits look good.  The issue about charges-and-fields is tracked elsewhere, and there is more work to be done on the MovableDragHandler due to https://github.com/phetsims/together/issues/131, but I think the core issue here has been addressed.  Closing.
