### ISSUE TITLE
layout options for NumberControl

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#217]
NumberControl currently has a fixed layout, which looks like this:

![screenshot_06](https://cloud.githubusercontent.com/assets/3046552/12995494/1138d548-d0e5-11e5-936c-73bbc0814c15.png)

Other desired layouts:

(1) Similar to above, but with arrow buttons on either side of value. Eg in Bending Light:

![screenshot_09](https://cloud.githubusercontent.com/assets/3046552/12995554/7f78bc62-d0e5-11e5-80a3-a29d2f111132.png)

(2) "Three lines" option. Label at the top. Independent alignment options ('left', 'center', 'right' ) for label and value+buttons.  Eg in Rutherford Scattering mockups:

![screenshot_05](https://cloud.githubusercontent.com/assets/3046552/12995504/1edb39de-d0e5-11e5-8a74-f9fd88378ff1.png)

Not sure what the best way of specifying these layouts is.  The easiest is certainly to give each layout a `{string} layoutName` and write different layout code specifically each.  The most general (and more complicated) would be to pass in an optional function that handles layout.

**Comment by pixelzoom** [comment]
Btw... This came up during Rutherford Scattering design meeting.  There are lots of places in PhET sims where we combine a label + value + arrow buttons (aka "tweakers") + slider into a single logical UI component.  And apparently developers have been creating (or copying) this component repeated.  Adding more flexible layout to NumberControl would allow it to replace a lot of these implementations.

**Comment by pixelzoom** [comment]
Alternatively, we could standardize on 1 layout.  There would be lower cost in the option, but I think it's unlikely.

**Comment by pixelzoom** [comment]
Assigned to @ariel-phet to evaluate whether we have all of the requirements and decide who should work on this.

**Comment by ariel-phet** [comment]
@pixelzoom it looks like you have captured the requirements above.

I think this would be a good project for @phetsims/schmitzware so that he can get his hands dirty with common code as there is some possibility common code type issues will arise in unit rates. Please let me know if you think that seems reasonable, but assigning to him for the moment. 

Marking as high priority, since it seems like this work would be good to wrap into the finishing off of Rutherford Scattering.

**Comment by pixelzoom** [comment]
> Please let me know if you think that seems reasonable

Yes, seems reasonable.

**Comment by pixelzoom** [comment]
In addition to layout options, there are some additional options that should be added for subcomponents. (E.g. xMargin and yMargin for ArrowButton.)

**Comment by pixelzoom** [comment]
Adding developer-meeting label. Other developers, please review the 3 layouts shown in https://github.com/phetsims/scenery-phet/issues/217#issue-133128208.  Are these general sufficient? Or are there others that have not been identified?

**Comment by pixelzoom** [comment]
@schmitzware asked about priority. @ariel-phet replied via email:
> I think ideally it would happen with the Rutherford work, since it would make the sim more maintainable. However, please consult Chris as to when he thinks it would be appropriate, if he feels it is fine to wait, I would be OK with that, but my guess is we will want to make the changes before we do acceptance testing.

I'm comfortable with deferring this. Getting going on unit-rates is probably more important. So that would be my first choice.

Second choice would be to just add the layout needed by rutherford-scattering, use it only in rutherford-scattering, and not try to back port to any other sims.

**Comment by pixelzoom** [comment]
Assigning to @ariel-phet to decide how to proceed (see my comments immediately above.)

**Comment by ariel-phet** [comment]
@pixelzoom sounds good on your first choice, adjusting to low priority.

**Comment by jessegreenberg** [comment]
Just looking through cases I could see of "slider + value + arrow buttons", I think options described in https://github.com/phetsims/scenery-phet/issues/217#issue-133128208 covers the different layouts.

**Comment by pixelzoom** [comment]
Removing developer-meeting label, since the priority of this issue has been set to low.

**Comment by pixelzoom** [comment]
Assigned to me at 7/14/16 status meeting.

**Comment by pixelzoom** [comment]
scenery-phet.ProbeNode uses a pattern for styling the look of the probe. See `glass` and `crosshairs`. After consulting with @samreid, I used a similar approach for creating layout functions in NumberControl.  

For lack of better names, see `CREATE_LAYOUT_FUNCTION_1`,  `CREATE_LAYOUT_FUNCTION_2` and `CREATE_LAYOUT_FUNCTION_3` in NumberControl, which create predefined layouts that can be customized via options.  The predefined layouts correspond to the 3 layouts depicted in https://github.com/phetsims/scenery-phet/issues/217#issue-133128208.

scenery-phet demo was modified to demonstrate each of the predefined layouts, plus a client-specific layout.  Run the demo with query parameters `?screens=2&component=NumberControl`.

@samreid Since you and I have discussed this, would you mind reviewing?

**Comment by pixelzoom** [comment]
In retrospect, I think that perhaps the predefined functions should have camel case names.  E.g., `createLayoutFunction1` instead of `CREATE_LAYOUT_FUNCTION_1`.

**Comment by samreid** [comment]
Adding a high priority label to put it on my to-do list.

**Comment by samreid** [comment]
I've finished reviewing the changes to NumberControl and its example usage in SlidersView.  Generally, things look great.  Here are some more details:

SlidersView.js line 91 is written like so:
```js
resize: false, // workaround for slider
```
Can you elaborate on why a workaround is needed for the slider, and what the workaround does?

This code comment looks like it is referring to the old name for the functions, it should be updated:
```js
// (see CREATE_LAYOUT_FUNCTION_*) or create your own function.
```

It is generally an antipattern to define a Node subclass that has exactly one child.  For instance, let's say I have a node subclass called "MyTriangle" which extends Node and adds children = [Path].  In this case, MyTriangle should be rewritten to extend Path.  It appears NumberControl also follows the pattern of "extends Node but has exactly one child" but I cannot find any way around it, aside from using static functions like NumberControl.create(..) that would create the NumberControl (which I advise against because `new NumberControl` is more idiomatic).  So this may be left as it is, but I thought I'd bring it up in case you have any ideas or comments.

**Comment by pixelzoom** [comment]
(1) and (2) addressed in above commit.

Re (3)... I considered adding the subcomponents (titleNode, numberDisplay, slider, leftArrowButton, rightArrowButton) directly to NumberControl, then having `options.layoutFunction` be responsible only for relative placement of the subcomponents.  This complicated the implementation and made it impossible to leverage VBox and HBox (which are very useful for this type of layout, since scenery still lacks general layout management).  So in this case, I think it's preferable to live with NumberControl having a single child.

**Comment by samreid** [comment]
The revisions look good and your comment makes sense, closing.
