### ISSUE TITLE
Why are LightRaysNode widths discrete?

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#247]
According to the docs in LightRaysNode, it supports only 3 line width (not continuous).  This leads to awkward situations like this one in CCK where just changing the voltage by 1 volt:

![volts](https://cloud.githubusercontent.com/assets/679486/16932206/36e7c558-4d02-11e6-96ac-12164310250e.gif)

Scenery/canvas/svg all support continuous line widths, why not use them?  Assigned to @pixelzoom since he was the original author and familiar with use cases.

**Comment by pixelzoom** [comment]
scenery-phet.LightRaysNode a port of piccolo-phet.LightRaysNode, which is a port of phetgraphics.LightRaysGraphic.  I was responsible for all 3 of these implementations. I don't recall for certain, but thinking back to circa 2004, I believe the I used integer line widths because it improved performance of the Java implementations.  I have no idea if using non-integer lineWidth in JavaScript has any performance penalty, but it seems like it might be prudent to investigate/experiment since there are so many scenery.Line instances being animated. Or consider re-implementing scenery-phet.LightRaysNode using CanvasNode.

**Comment by samreid** [comment]
I suspect that svg performance for non-integer line width would be the same as integer line width on all or nearly all browsers.  Also, using canvas would be disastrous for CCK because a separate raster would be created for each of N bulbs, causing memory issues.

I'm not opposed to a performance test, if one is easy to implement.  I'll leave this assigned to me for investigation.

**Comment by samreid** [comment]
On second thought, discretizing the light rays *does* improve performance because they need to be changed less frequently.

Still, this discrete jump seems detrimental in CCK and in other use cases.

Testing in Acid Base Solutions, there is a point where changing the "weaker/stronger" slider by 1 pixel changes the light bulb brightness disproportionately:

![lines](https://cloud.githubusercontent.com/assets/679486/16987484/b84935f8-4e49-11e6-8353-18fb73be9052.gif)

I recommend to implement continuous line widths and compare performance on iPad.

**Comment by samreid** [comment]
I developed a continuous measure between the max and min.

On iPad3 running requirejs mode of Acid base solutions screen 2, with initial concentration maxed out and dragging the strength slider continuously, I see the following performance:

continuous lines: 4FPS
discrete lines: 4FPS

Hence the continuous lines don't seem to slow things down for this case (bottleneck is likely elsewhere).  I'll proceed with updating to use the continuous logic.

**Comment by samreid** [comment]
In the preceding commit, the rays are continuous instead of discrete.  I tested in Acid Base Solutions' 2nd screen and it looks good.  @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
Inspected the commit, looks good, closing.
