### ISSUE TITLE
NumberKeypad: add ability to constrain what's entered

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#272]
In unit-rates, number entry needs to be constrained to 2 decimal places. That seems impossible to accomplish with NumberKeypad, which only allows you to specify `options.maxDigits`.  @jbphet am I missing something?

**Comment by pixelzoom** [comment]
unit-rates also needs to constrain the number of digits in the integer portion of the number entered. Basically, I need to be able to enter dollars and cents in some places ($0.01 to $99.99), and pounds in other places (0.1 to 99.9).    

It sure would be a lot more general if the API included a function to validate (accept or reject) each key press.

**Comment by jbphet** [comment]
I just looked through the code base, and it appears that ```decimalPointKey``` - the option attribute that is used to turn on the decimal point button - has only been used in projectile-motion and unit-rates thus far.  The other sims that use NumberKeypad have only allowed the entry of integers.  So, it looks like this is the first time that we need to restrict the number of decimal digits.

Generalizing this to have a validation function sounds like a good idea to me.

**Comment by jonathanolson** [comment]
I also had recorded that KeypadPanelNode (unit-rates) enabled the decimal point button, but I could be wrong.

> It sure would be a lot more general if the API included a function to validate (accept or reject) each key press.

Sounds great.

**Comment by pixelzoom** [comment]
I had proposed providing this feature via options, but that's proving to be awkward.  Each constraint function will potentially have its own set of options.  For example, the current `maxDigits` option is really specific to a "constrain to integer" function, which was useful in arithmetic and other @jbphet sims.  In unit-rate, I need to constrain to a currency range ($0.00-$99.99) or weight (0.0-99.0 lbs). For that constrain function, `maxDigits` is irrelevant and I need other options (number of digits in integer and fraction portions). 

@jbphet @jonathanolson suggestions on how to provide this feature?

**Comment by jonathanolson** [comment]
Predicate function might be nice?

Do we (or should we) disable buttons that, when pressed, would break a constraint?

**Comment by pixelzoom** [comment]
@jonathanolson asked:
> Do we (or should we) disable buttons that, when pressed, would break a constraint?

That (and other unsupported features) has certainly been proposed during area-model-multiplication design.

**Comment by pixelzoom** [comment]
@jonathanolson suggested:
> Predicate function might be nice?

Predicate functions return true/false based on whether their input(s) satisfy some condition(s).  Unfortunately, it's a little more complicated than returning true/false to accept/reject a keystroke, as evidenced by the "accept and replace 0" behavior that is currently implemented.  E.g., if the current value is "0" and you enter "1", then the value becomes "1".

**Comment by jonathanolson** [comment]
> E.g., if the current value is "0" and you enter "1", then the value becomes "1".

The button press would presumably recognize how the number/string would change (e.g. "0" => "1") and would run the predicate on the result ("1")? Whether the button is enabled would be:
```js
for ( var button ) {
  digitArrayProperty.link( function( digits ) {
    button.enabled = allowedPredicate( button.applyTo( digits ) );
  } );
}
```
with the ```applyTo``` returning a modified copy of the array of digits (with enum)?

**Comment by jbphet** [comment]
Since enabling and disabling buttons is only proposed, I'd be a little inclined to push back on that.  Most people's experiences with keypads - on calculators, computers, and even touch devices - don't have keys changing their enabled states.  To solve the immediate validation problem, wouldn't it work to have an optional function that takes the string value and the key press and returns the resulting value?  Something like:
```js
   this.digitString.set( options.validateAndUpdate( this.digitString.get(), key ) );
```
We could have some stock validation functions available statically on the NumberKeypad object.  If we go that far, these could even be objects that could be constructed with parameters such as length.

**Comment by pixelzoom** [comment]
> To solve the immediate validation problem, wouldn't it work to have an optional function that takes the string value and the key press and returns the resulting value? 

But that optional function has addition options (like `maxDigits`) that apply to it. How do you propose to specify those function-specific options?

**Comment by pixelzoom** [comment]
@jbphet: And `digitString` has been gone for days, so I'm guessing that you might be looking at a stale working copy.

**Comment by pixelzoom** [comment]
Could also use an approach like the `sensorTypeFunction` option in scenery-phet.ProbeNobe.

**Comment by pixelzoom** [comment]
I used the approach that @samreid used for the `sensorTypeFunction` option in scenery-phet.ProbeNobe.  The validator that was currently implemented (maxDigits with 1 leading zero) is available via `validateMaxDigits`. 

@jbphet @jonathanolson please review.

**Comment by pixelzoom** [comment]
If this approach looks OK, I'll proceed with adding `validateCurrency` and `validateWeight` in unit-rates.

**Comment by pixelzoom** [comment]
@jbphet (especially) and @jonathanolson ping.

**Comment by jonathanolson** [comment]
Implementation looks good, with the caveats:

1. Doesn't handle validation of what digit-strings are allowed, but what button presses do. This would make it harder to add another similar filter (e.g. only allow 2 digits to the left of the decimal point, but 4 to the right) as you'd need to duplicate a lot of button behavior, but it allows for more customizability. My previous recommendation was to hard-code what operations each of the buttons would do, and validate the potential result. Is there a potential for the keypad to have the buttons do different operations?
2. Doesn't handle validation of backspace (presumably not much of an issue)
3. Relies on string comparisons instead of an array of a digit enum. Backspace key, digit length computation and other things will break if the decimal point string is i18nized (embedding marks, and will fail during string tests even if the marks are stripped off).

**Comment by pixelzoom** [comment]
I agree with everything @jonathanolson.  There are rather fundamental problems with the basic implementation of NumberKeypad.  So I guess the question is: Do we do a total rewrite now or later? @ariel-phet your thoughts? (Keeping in mind that I do not have time for a total rewrite, and I needed this functionality a couple of weeks ago.)

**Comment by jbphet** [comment]
I've mentioned this in a couple of other GitHub issues, but I'm starting to feel like having the keypad and the validation logic separated would make this easier.  That way we could have an object like "KeypadAccumulator" that contained the logic for accumulation and validation, and we could have overridable default validation functions (similar to SimpleDragHandler) and we wouldn't have to have all the logic in the keypad itself.  That way, if some new and unusual situation came up, we could just write a new variant of KeypadAccumulator instead of copying and changing the whole keypad.

**Comment by jbphet** [comment]
I know this probably isn't what @pixelzoom wanted to hear, since he needs the functionality now.  Maybe there is a short term fix that can be done to move him forward and we can schedule the work to refactor a couple of months out.  I'd be up for doing it, since I like the sound of it, but it's all a matter of time and priorities.  Adding @ariel-phet to the dialog to help with that part.

**Comment by ariel-phet** [comment]
Discussed with @jbphet  and as long as @pixelzoom is on board for this architectural approach, I think it sounds like a good idea.

@jbphet and @pixelzoom should have a high level architectural discussion, and @jbphet will get some assistance from @aadish with implementing.

**Comment by pixelzoom** [comment]
@ariel-phet What is the timeframe for doing this?  It needs to be usable in unit-rates by the end of December.

**Comment by ariel-phet** [comment]
@pixelzoom well, I think @aadish can hop on it right away (with @jbphet supervision) once you two come up with an architectural plan. So it would basically be his top priority.

**Comment by pixelzoom** [comment]
@ariel-phet Regarding architectural plan...
(1) Design of NumberKeypad *and* NumberEntryControl should be completed before any reimplementation begins, lest we repeat the same mistake.
(2) @jonathanolson should be included in design and architectural planning, since he's had good feedback and is responsible for NumberEntryControl.
(3) There are valuable architectural ideas scattered throughout NumberControl issues. These come to mind:  https://github.com/phetsims/scenery-phet/issues/280#issuecomment-260466199, https://github.com/phetsims/scenery-phet/issues/272#issuecomment-261613834, https://github.com/phetsims/scenery-phet/issues/279#issuecomment-259204834 and https://github.com/phetsims/scenery-phet/issues/272#issuecomment-261169343.
(4) I don't have time to be involved in this. My interest is in using it to complete unit-rates, which I am now 2+ weeks behind on.

**Comment by jbphet** [comment]
@aadish and I met today and tried to put together a design that incorporates the architectural ideas that @pixelzoom listed above plus some others that came up during a meeting with @pixelzoom, @jonathanolson, @aadish and me on Nov 21.  I'll try to get the four of us together early next week and see if we can reach a decision on how to move forward.

**Comment by jbphet** [comment]
`NumberKeypad` has been replaced by `Keypad`, see https://github.com/phetsims/scenery-phet/issues/283.  `NumberKeypad` is now deprecated, and all further keypad work will be done in `Keypad` and its collaborators.  Closing.

**Comment by samreid** [comment]
There are still TODOs marked for this issue, discovered during https://github.com/phetsims/chipper/issues/946

**Comment by samreid** [comment]
Unassigning until we return our attention to NumberKeypad.

**Comment by zepumph** [comment]
Just the todos here.

**Comment by zepumph** [comment]
TODOs have been removed. I added support for validateKey in NumberEntryControl, which will work, as long as you make sure to note how maxDigits behaves from that. I added a note in the option documentation since it wasn't obvious otherwise, and there is no real way to test the validateKey function's guts. I think we are ready to close this issue, as there are no more TODOs.
