### ISSUE TITLE
Toolbox: Design requirements

### ISSUE THREAD

**Issue by arouinfar** [phetsims/scenery-phet#289]
In https://github.com/phetsims/circuit-construction-kit-common/issues/224, @samreid commented 
> In our simulations with toolboxes, typically a "click" (down then immediate up) leads to this behavior: The object flickers large for a second. This is probably not what the user intended to happen.
I asked @arouinfar in #63 what the behavior should be, and she replied:
"the object is grabbed (full size) but can immediately be dropped back into the toolbox -- like the tools in Bending Light."
I wanted to discuss this more thoroughly and understand our reasoning for this behavior and discuss whether it should be changed. Is this current behavior the behavior because it is easy to implement? Because it is rare for students to click and release on those objects? Because we want them to learn that they are supposed to drag it? (does a flicker accomplish this?) What if a click and release made the object appear in the play area (adjacent to the toolbox)? Or what if a click and release just did nothing? (that is, didn't show the flicker). There are more possibilities as well, my main point is to start a discussion about what we want the ideal user experience to be.

@samreid has asked several good questions that merit a broader discussion about a general Toolbox at design meeting.

(@samreid please feel free to rename this issue if "Toolbox" isn't the appropriate name for this component.)

Relevant issues:
* https://github.com/phetsims/circuit-construction-kit-common/issues/224
* https://github.com/phetsims/circuit-construction-kit-common/issues/63

**Comment by emily-phet** [comment]
@ariel-phet - Is this an urgent issue? Could this be put on hold for a bit, for some keyboard navigation work to evolve? Decisions here will significantly impact keyboard nav, so it would probably be beneficial to include that expertise in the discussion, and we will only gather more of that with time. I can also ask Taliesin to take some time to investigate this specific interaction once she's returned from traveling in March.

**Comment by ariel-phet** [comment]
@emily-phet I think it is urgent in the sense that we need to begin the discussion. For instance, we had a design discussion (several) about our dialogue boxes, although nothing has been implemented yet. So we want to get this discussion going and start to understand the various issues. As noted on design meeting, all interested parties are welcome, so certainly would be good to have you and @jessegreenberg at the initial meeting.

**Comment by emily-phet** [comment]
@ariel-phet Certainly your call whether or not to discuss, but my concern is that even if @jessegreenberg and I are there, we don't have *any* answers to the questions that will come up. Various behaviors will be discussed and neither @jessegreenberg or I will be able to indicate what's feasible, or best, for keyboard nav. It will take some investigation to determine what are some reasonable approaches to discuss from the keyboard nav side of things, and Taliesin is really the person with the best expertise to do that. Once she's returned from travel she will be able to quickly prepare a set of options for discussion, but that is not something I want to ask her to do until she returns. So you'll be having a discussion with a central and significant set of information missing.

Note: I only bring up the suggestion to pause on this since it sounded like an attempt to standardize across sims (rather than focus solely on CCK), which is aligned with the goals of standardizing the keyboard nav across sims for common features like toolboxes. 

And...just to throw my 2cents into the original issue - I think having a "click" result in enlargement of the toolbox item helps indicate that the icon *does* something, and cues that it would be useful to find out what it does. If you click and nothing happens at all, someone could get the impression that nothing happens, or it is broken (since the icon is inside of a container it may not be clear to everyone that you should drag it out). If you click and it appears outside the container, but clicking on it does not move it back in the container...again someone might not recognize that you drag it in/out - they may think you click it in and out and they can't get it back in.

**Comment by arouinfar** [comment]
Notes for the design meeting discussion can be found in the HTML5 Sim Toolboxes doc located in:
PhET Files > PhET Design Resources > Design Resources - Sim Design > HTML5 Sim Toolboxes

The general consensus was that we would keep the toolbox behavior as-is, but could possibly investigate a longer flicker (~0.5s) on release.

Toolboxes are currently made on a sim-by-sim basis due to the varying needs of each sim (see notes for more discussion of sim-specific behavior). I don't believe there is currently any plan to create a scenery component for toolboxes, so this issue can likely be closed.

@samreid can you advise on the next steps that should be taken?

**Comment by ariel-phet** [comment]
@arouinfar I think make an issue for increasing the time delay of increased component size, but make this issue in CCK. @samreid can try it out in that sim, and then if all looks good we can consider generalizing. In the issue probably mention the idea of generalizing, and @samreid can decide where and how that should be done if all looks good (since we have several sims that use this enlargement strategy like FAMB Bending Light and such)

**Comment by ariel-phet** [comment]
@arouinfar I think once that other issue is made, this one can be closed

**Comment by arouinfar** [comment]
Thanks @ariel-phet. I've opened a new issue in the common CCK repo:
https://github.com/phetsims/circuit-construction-kit-common/issues/244
