### ISSUE TITLE
Misleading options for Bucket/BucketFront.

### ISSUE THREAD

**Issue by davisv007** [phetsims/scenery-phet#307]
While setting up a bucket with a caption for fractions-intro, we found that the label in bucketFront takes an option 'bucket.captionText' (line 53) . So naturally when trying to give an out caption to Bucket, we thought we should use the option 'captionText'. It took us a while to figure out that the option in Bucket itself is called 'caption'.  In line 53 of the Bucket model, we found that this.captionText is equal to options.caption. I suggest that these two options share the same name. 

assigning to @jbphet  to decide whats the best course of action.

**Comment by jbphet** [comment]
Good observation @davisv007.  I've updated the option to be called `captionText`, since there is already an option called `captionColor`, so it is probably best to clearly distinguish between the various separate attributes of a caption.

By the way, the bucket code is some of the oldest in our code base, so it won't be unusual to run into issues like this, and it's good to point out issues like this.

Also, if this were being written today, we'd probably have the buckets take a node for the label rather than separate attributes of a caption.  This would allow more general behavior, such as using or including icons in the label.  If you have a need to do this - i.e. include something other than text as part or all of the label - let me know (in a separate issue) and we can work together to "modernize" the bucket code a bit.

Back to @davisv007 for review and closure if the changes look good.

**Comment by davisv007** [comment]
Looks great!
I understand making this change affected multiple projects and I appreciate your promptness. 
We do in fact need the ability to add dynamic labels and pictures to our buckets in fractions-intro.
@michaelm396 and I would definitely like to work with you to modernize the bucket code. We'll create an issue shortly.  Thank you. 

Closing this issue now.
