### ISSUE TITLE
universal operations: add support for operands that are variable terms

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#357]
Summary of discussion with @amanda-phet about this feature that was proposed by @kathy-phet.

The universal operation control currently supports 4 operators (`+,−,×,÷`) , and integer operands in the range `[-10,10]`.   Universal operations are applied to terms on both sides of the scale. If there is no variable term on the scale, there is currently no way to create one on the scale using a universal operation.

The change request is to support operations with the `+` and `-` operators and operands that are variable terms.  The variable terms would have integer coefficients in the range `[-10,10]`, excluding zero -- i.e. `-10x,-9x,...,-x, x,..., 9x, 10x`.  Example operations: `+ 10x`, `+ -5x`, `− 5x`, `− -2x`.

The primary value of this change is in the game screen. It would allow us to include challenges that have variable terms on both sides of the equations.  There is little (no?) additional value for the Solving screen, but the control should be consistent in all screens.

Two challenges:

(1) Redesign the UI control so that an already-complex control doesn't become incomprehensible. 

(2) Implement support for operands that are constant or variable terms. This will be a full rewrite of the universal operation implementation.  No time estimate until this feature request gets more specific.

**Comment by pixelzoom** [comment]
The proposal that @amanda-phet described for me involves having the operators `[ +,−]` appear twice in the operator picker, with visual cues to indicate that one pair is applicable to constant terms and one pair is applicable to variable terms. Imo, that proposal has numerous problems, mostly relate to the duplication of operators − difficult to design effective visual cues, potentially confusing to students, difficult to describe (in specifications, classroom, teaching materials,..), difficult to instrument for a11y, complicated implementation that reflects the confusing UX, ...

Here's another proposal:

Operator picker with one instance of each of these operators. Default is `+`. 
`[ +,−,×,÷ ]`

Operand picker with these constant and variable terms, in this order.  Default is `1`.
`-10x, -10, -9x, -9, ..., -2x, -2, -x, -1, 0, 1, x, 2, 2x, ..., 9, 9x, 10, 10x`

For operators `[+,−]`, the full set of operands (constants and variable terms) is available.
For operator `×`, only the operands that are constants are available.
For operator `×`, only the operands that are _non-zero_ constants are available.

When switching from `[+,−]` to `[×,÷]` with a variable term operand selected, the operand changes to the constant with the same coefficient as the variable term.  E.g. if operand `10x` is selected, and you change the operator from `+` to `×`, then the operand changes to `10`.

**Comment by amanda-phet** [comment]
Thanks @pixelzoom this is a really good summary. 

I'd like to discuss the implications and timeline with @kathy-phet a bit. It sounds like this could push out the deadline for publishing this sim by at least a week, and we should weigh that with the benefits of having the sim published in time for our presentation at ISTE (already a tight timeline). 

I'd also like to wait until after interviews to decide on if we make this change because there's a chance that the component as-is (pickers with operator and operand) will be difficult for students to interpret, so if they need to be re-designed I'd want to do that before making such a costly change. However, @pixelzoom mentioned that this should not be a 1.1 feature as it will take many times longer to accomplish at a future date than it would to do now, so if we do it, it should be in the next month.

**Comment by pixelzoom** [comment]
Oops.  Somehow I accidentally created this issue in scenery-phet.  I'll move it to equality-explorer.
