### ISSUE TITLE
Problems with HelpContent

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#391]
Poking around in this file for https://github.com/phetsims/a11y-research/issues/113#issuecomment-402547376, I noticed that in friction some of the rows of help content don't have anything in the PDOM. I should make sure that there are assertions in place to keep this from happening. Here is a nice place, because we know that these Nodes will only exist if a11y is enabled, which means that there must be accessibility strings passed in for the PDOM.

**Comment by zepumph** [comment]
Next I need to do the same with labelWithIconList

**Comment by zepumph** [comment]
Next I need to add strings for friction so there aren't errors

**Comment by zepumph** [comment]
That should be good for now. That only main issue I see is that GFLB doesn't have any a11y strings for its custom HelpDialog content. Otherwise this issue is good to go.

**Comment by zepumph** [comment]
@jessegreenberg please review.

**Comment by jessegreenberg** [comment]
This looks good @zepumph, thanks. At first I was concerned that this would be too strict, but I agree that moving forward the keyboard help dialog will be designed along with the sim descriptions so making it required in the initial implementation seems like the right way forward. And since GFL:B has the help content descriptions now, there is no longer a special case. Closing.
