### ISSUE TITLE
Choose an optimal default size for the ResetAllButton

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#41]
Many usages of ResetAllButton are changing the default size by scaling or changing the radius.  We should find out what is the most popular size, and make it the new default.

**Comment by pixelzoom** [comment]
The default for ResetAllButton is currently `radius:24`.

Here are the sizes used by sims A-F:

> acid-base-solutions: scale:0.75
area-builder: radius:20, radius:22
arithmetic: default
balancing-act: radius:20 
balancing-chemical-equations: default, scale:0.8
balloons-and-static-electricity: scale: 0.96
beers-law-lab: scale:1.32
bending-light:  radius:19
black-body-spectrum: default
build-an-atom: scale:0.85
calculus-grapher: default
capacitor-lab-basics: radius:25
charges-and-fields: default
circuit-construction-kit-common: default
color-vision: radius:18
curve-filling: scale:0.75
energy-forms-and-changes: default, radius:20
energy-skate-park-basics: scale:0.85
estimation: default
expression-exchange: default
faradays-law: scale:0.75
fluid-pressure-and-flow: default, radius:18
forces-and-motion-basics: radius:23
fraction-comparison: radius:24
fraction-matcher: default
friction: radius:22
function-builder: default

The most common value is "default".  So I see no reason to change the default, unless you suspect that sims G-Z deviate from this pattern.

Most (all?) of the sizes are within a few pixels of each other, which begs the question of whether they need to be different.  But I suspect that yes, they need to be different, because pixel polishing often involves small changes like this.

So... @samreid Are you OK with closing this issue?

**Comment by samreid** [comment]
Yes, thanks for this review.  Seems like we are already in good shape, closing.
