### ISSUE TITLE
Factor out "space to grab/release" node from balloonInteractionCueNode

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#419]
For https://github.com/phetsims/friction/issues/142 we need the same Node, so I'm going to move this here and convert the BASE usage too. Tagging @jessegreenberg so he knows I'm mucking with his sim.

**Comment by zepumph** [comment]
@jessegreenberg can you please review this. @samreid was worried about how I deleted a string key from BASE that is published with the sim.  How would you recommend proceeding? We could revert the changes in BASE and just have two copies of this simple node, one in BASE and one everywhere else.

Or we can feel ok about losing all the translations because the refactor is worth it.

Or we can do something else. I'm not very familiar with these sorts of translation issues, and so I don't know what is best to do.

**Comment by samreid** [comment]
> @samreid was worried about how I deleted a string key from BASE that is published with the sim.

I'm more uncertain than I am worried.  It seems like it should be OK, and that if rosetta is working with the latest string keys, then there won't be a problem that is visible to the end user, there would just be a stale key/value pair left over in pre-existing translations.

**Comment by zepumph** [comment]
Tagging @jbphet for ground truth comment.

**Comment by jbphet** [comment]
If the string key is simply deleted from the English strings file, that string will stop appearing to translators right away, i.e. before the updated version of the simulation is published.  This is because Rosetta extracts the list of strings used in a sim from the published version, then retrieves the master version of the strings from GitHub, and only presents each individual string to the user if it appears in both the sim and the English strings file (at least I'm *fairly* certain that this is how it operates).  This means that any translators who try to add a new translation to BASE between the time that the string is deleted from the strings file and the publication of the updated simulation will be unable to translate that string, or to update an existing translation for that string.  Once the updated version of BASE is published, this problem will go away.

Hopefully this answers your request for a "ground truth comment", please let me know if more is needed.

**Comment by zepumph** [comment]
RE: my commit above:

@jbphet is it possible to add a comment to the string key like:
```
  "toGrabOrRelease": {
    "value": "to <b>Grab</b> or <b>Release</b>"
    "comment":"this is only needed for old versions of the simulation, and should be removed once 1.5 is published to the website.
  },
```

**Comment by jbphet** [comment]
> @jbphet it feels very strange that these strings are taken from master. I would have expected them to be taken from the sha of the published sim version

Sorry, you're correct, that's what it does.  I was momentarily confused - it's babel that keeps everything on master and doesn't use branches.  My bad.

**Comment by zepumph** [comment]
Ok then, that makes a lot of sense. I am going to revert me most recent commit to add back in the string key then.

**Comment by zepumph** [comment]
Thank you for the clarification!

**Comment by zepumph** [comment]
Alright. @jessegreenberg, as this is common code (albeit a simple node), and BASE is your sim, please review the first two commits of this issue.

**Comment by zepumph** [comment]
Hey, after using this type a bit more, I think I'm going to rename it from `SpaceToGrabReleaseNode` to `GrabReleaseCueNode`. It feels more general.

**Comment by zepumph** [comment]
Alright all you.

**Comment by jessegreenberg** [comment]
Thanks @zepumph, all looks good. Closing.
