### ISSUE TITLE
Add color option to slider thumb in HeaterCoolerNode

### ISSUE THREAD

**Issue by chrisklus** [phetsims/scenery-phet#435]
Described in https://github.com/phetsims/energy-forms-and-changes/issues/132#issuecomment-445420989

**Comment by chrisklus** [comment]
All set. Tested in EFAC, SOM, SOMB, and GP. Assigning to @pixelzoom for review.

**Comment by pixelzoom** [comment]
Two new options were introduced in `HeaterCoolerNode` and `HeaterCoolerFront`:

```js
thumbFillEnabled: new Color( 195, 196, 197 ),
thumbFillHighlighted: new Color( 222, 222, 222 )
```

Issues:

(1) The options are undocumented.  Presumably `{Color|string|null}`?
(2)  The default values are duplicated.
(3) Default Color values could be replaced with CSS color strings.
(4) Default values whose value involves `new` should be factored out as constants.

I noticed that issues (2) and (4) also apply to options `baseColor`, `labelFont`, and `thumbSize`.

**Comment by chrisklus** [comment]
>The default values are duplicated.

Literally all of the options in HeaterCoolerNode are duplicated in HeaterCoolerFront. I thought this was odd as well. Suggestions for how to proceed?

**Comment by pixelzoom** [comment]
@chrisklus asked:
> Suggestions for how to proceed?

Like this:

```js
// Copyright 2018, University of Colorado Boulder

define( require => {
  'use strict';

   // modules
  const HeaterCoolerBack = require( 'SCENERY_PHET/HeaterCoolerBack' );
  const HeaterCoolerFront = require( 'SCENERY_PHET/HeaterCoolerFront' );
  const Node = require( 'SCENERY/nodes/Node' );
  const sceneryPhet = require( 'SCENERY_PHET/sceneryPhet' );
  
  // const
  const DEFAULT_BASE_COLOR = 'rgb( 159, 182, 205 )';

  /**
   *
   * @author Chris Malley (PixelZoom, Inc.)
   */
  class HeaterCoolerNode extends Node {

    constructor( heatCoolAmountProperty, options ) {

      options = _.extend( {
        
        // {Color|string} color of the body, applied to HeaterCoolerBack and HeaterCoolerFront
        baseColor: DEFAULT_BASE_COLOR,

        // {*} options to customize HeaterCoolerBack
        backOptions: null,

        // {*} options to customize HeaterCoolerFront
        frontOptions: null

      }, options );

      assert && assert( !options.backOptions.baseColor, 'HeaterCoolerNode sets baseColor for HeaterCoolerBack' );
      const heaterCoolerBack = new HeaterCoolerBack( heatCoolAmountProperty, _.extend( options.backOptions, {
        baseColor: options.baseColor
      } ) );

      assert && assert( !options.frontOptions.baseColor, 'HeaterCoolerNode sets baseColor for HeaterCoolerFront' );
      const heaterCoolerFront = new HeaterCoolerFront( heatCoolAmountProperty, _.extend( options.backOptions, {
        baseColor: options.baseColor,
        leftTop: heaterCoolerBack.getHeaterFrontPosition()
      } ) );

      assert && assert( !options.children, 'HeaterCoolerNode sets children' );
      options.children = [ heaterCoolerBack, heaterCoolerFront ];

      super( options );

      // @public Dispose function used for GC
      this.disposeHeaterCoolerNode = function() {
        heaterCoolerBack.dispose();
        heaterCoolerFront.dispose();
      };
    }

    // @public
    dispose() {
      this.disposeHeaterCoolerNode();
      super.dispose();
    }
  }
  
  // Used by HeaterCoolerFront and HeaterCoolerBack
  HeaterCoolerNode.DEFAULT_BASE_COLOR = DEFAULT_BASE_COLOR;

  return sceneryPhet.register( 'HeaterCoolerNode', HeaterCoolerNode );
} );
```

**Comment by chrisklus** [comment]
@Denz1994 is going to handle the above changes not related to color options for the slider thumbs over in https://github.com/phetsims/scenery-phet/issues/423.

I will update these colors once we have a color with better contrast to the gray bucket, see https://github.com/phetsims/energy-forms-and-changes/issues/132#issuecomment-445579348

**Comment by pixelzoom** [comment]
This is incorrect in HeaterCoolerNode.js:

```js
44  baseColor: new Color( DEFAULT_BASE_COLOR ),
```

It should be:

```js
44  baseColor: DEFAULT_BASE_COLOR,
```

**Comment by pixelzoom** [comment]
I think I see why you did the above.  HeaterCoolerFront and HeaterCoolerBack are assuming `{Color} baseColor`, so that they can do operations like `options.baseColor.brighterColor`.   That's a bad assumption.  `baseColor` should be documented as `{Color|string} baseColor` in both of those classes.  And if the class needs to operate on `baseColor` as a `Color`, it should be calling `Color.toColor( options.baseColor )`.

Another problem... The whole point of adding `HeaterCoolerNode.DEFAULT_BASE_COLOR` was to use as the default value for `baseColor` in   HeaterCoolerFront and HeaterCoolerBack.  That has not been done.  I still see `new Color( 159, 182, 205 )` duplicated in both of those classes.

**Comment by pixelzoom** [comment]
This issue stalled out 2+ years ago. Self-assigning to figure our where this is at, and propose a path forward.

**Comment by pixelzoom** [comment]
Here's what remains to be done:

- [ ] Specify `DEFAULT_BASE_COLOR` in one place, use in the other 2 places. HeaterCoolerNode wold be the logical place for this, but that would create a circular dependency.  So HeaterCoolerFront is probably the next-best.
- [ ] Refer to "stove" consistently, instead of "stove" in HeaterCoolerFront and "burner" in HeaterCoolerBack.

I'll take care of this.

**Comment by pixelzoom** [comment]
Each of the 3 remaining items is covered by one of the 3 commits above.   Tested in a scenery-phet demo, and a number of sims that use these classes (EFAC, Gas Properties, ...).  Since this issue had stalled out, I'm not going to risk that again by requesting a review.  I'll mention these changes in Slack dev-public channel.  

Closing.
