### ISSUE TITLE
HeaterCoolerNode: default slider thumb looks disabled

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#443]
At a meeting last week (I forget which one) there was consensus that the defaults for HeaterCoolerNode make the thumb look disabled.   So this needs to be revisited by the design team.  Assigning to @arouinfar since I encountered this in the context of Gas Properties.

The relevant options appear in HeaterCoolerFront, the front part of HeaterCoolerNode.  They are:

```js
        thumbFillEnabled: '#c3c4c5', // {Color|string|null}
        thumbFillHighlighted: '#dedede' // {Color|string|null}
```

Here's a screenshot from Gas Properties:

![screenshot_942](https://user-images.githubusercontent.com/3046552/50115305-32633d00-0204-11e9-8f41-8677cd9317ac.png)

**Comment by arouinfar** [comment]
@pixelzoom I think a pale yellow will work well for the thumb. I think it's a reasonably neutral color that doesn't interfere with the red/blue slider track, while still looking interactive.

Let's go with:
thumbFillEnabled: `#ffffd9`
thumbFillHighlighted: `#fffff2`

Here are a few screenshots showing it in context.
![screen shot 2018-12-17 at 4 40 40 pm](https://user-images.githubusercontent.com/8419308/50122596-92fd7480-021a-11e9-81ee-3aa2a29fe77a.png)
![screen shot 2018-12-17 at 4 40 50 pm](https://user-images.githubusercontent.com/8419308/50122597-92fd7480-021a-11e9-8d54-5d0acf52973c.png)
![screen shot 2018-12-17 at 4 41 00 pm](https://user-images.githubusercontent.com/8419308/50122598-92fd7480-021a-11e9-9f72-6084bb2f8491.png)

**Comment by arouinfar** [comment]
Not sure if @pixelzoom or @chrisklus would address, so assigning to both.

**Comment by pixelzoom** [comment]
When we do this, we should be sure to evaluate in sims that use HeaterCoolerNode, and notify responsible designers/developers of those sims that there has been a change.

**Comment by pixelzoom** [comment]
> ... which sims use HeaterCoolerNode? ...

energy-forms-and-changes
gas-properties
states-of-matter
states-of-matter-basics

**Comment by chrisklus** [comment]
@arouinfar I investigated this change a bit. 

As you have in your mockup, the horizontal center line needs to be something dark like black, but I think it's a little overpowering the way I have it on the left, below. So I tried increasing the line width of the thumb outline to 2, similar to your EFAC mockup in https://github.com/phetsims/scenery-phet/issues/443#issuecomment-448041916, but that seemed like a little much as well.

What do you think?  

![image](https://user-images.githubusercontent.com/5618316/50170767-e79dff80-02ad-11e9-9a87-c4647685511d.png)

**Comment by chrisklus** [comment]
Ooo I forgot we don't need whole numbers for this kind of thing, so I tried 1.4 for the line width and I think it looks more like your mockup

![image](https://user-images.githubusercontent.com/5618316/50171442-b45c7000-02af-11e9-8e1c-660c0a47080f.png)

**Comment by arouinfar** [comment]
Thanks for confirming @pixelzoom!

@chrisklus https://github.com/phetsims/scenery-phet/issues/443#issuecomment-448303230 looks awesome!

**Comment by chrisklus** [comment]
All set. @arouinfar anything left to do here?

**Comment by pixelzoom** [comment]
Code change look good to me, so self unassigning.

**Comment by arouinfar** [comment]
@jbphet pointed out that the pale yellow looked a bit too much like the EFAC background color, and I agree. Since HeaterCoolerNode is often central to sim interaction, I think the thumb could be a bit brighter.

I iterated on a few different color options including minty green ("kinda ugly") and bright yellow ("garish"), before trying a bright teal, similar to the default hover color.

@jbphet @ariel-phet @kathy-phet and @KatieWoe and I all thought the teal looked nice.
* It's an eye-catching color, but isn't too loud
* While a variant of blue, the teal color does not clash (or match) the red/blue track gradient, even in colorblind preview modes.

@chrisklus @pixelzoom since you are also responsible devs for sims using HeaterCoolerNode, I want to check in with you to see what you think about this proposal.

thumbFillEnabled: `#71edff`
thumbFillHighlighted: `#bff7ff`

![image](https://user-images.githubusercontent.com/8419308/50253329-1ba91b80-03a7-11e9-966b-b673d93ccde6.png)
![image](https://user-images.githubusercontent.com/8419308/50253342-2663b080-03a7-11e9-872e-65e963f3e809.png)
![image](https://user-images.githubusercontent.com/8419308/50253358-324f7280-03a7-11e9-830f-f428609a8d4e.png)

**Comment by pixelzoom** [comment]
I like the teal.

**Comment by chrisklus** [comment]
I think the teal clashes with the water a little bit, so I prefer the light yellow, but I don't feel strongly about this.

Happy to make the change to teal if everyone's signed off.

**Comment by arouinfar** [comment]
@pixelzoom @chrisklus thanks for the feedback.

@chrisklus, please go ahead and make this change, as teal was the most preferred color.

**Comment by chrisklus** [comment]
All set @arouinfar

**Comment by arouinfar** [comment]
Looks great, thanks @chrisklus!
