### ISSUE TITLE
Code review GrabDragInteraction

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#447]
@jessegreenberg this file has gotten pretty complicated through its development over the last few months. It would be good to have some review before we take things to RC.

Here are some things to focus on:
* Logic that splits/alternates between grabbable and draggable interaction modes
* API: could any of the options be improved on? For example there is `onGrabbable` and `onGrab` callbacks, which serve similar but different purposes.
* Should this be a mixin? It kinda is right now, but in a sloppy way.

Before beginning, I'm going to write a few tests for the file. Please hold off until I have committed those. (I'll commit them here).

**Comment by zepumph** [comment]
Alright I renamed the file, and added tests. Ready for review.

**Comment by zepumph** [comment]
@emily-phet let us know that we can proceed with the Friction RC before this is worked on. Though it would be good to do while the code is still somewhat fresh. Leaving priority up to @jessegreenberg.

**Comment by jessegreenberg** [comment]
THanks @zepumph this is looking really nice. Documentation in this file is great. As part of review I am going to try to use in BASE.

**Comment by jessegreenberg** [comment]
This looks really nice, nice work @zepumph! I had no trouble at all using this in phetsims/balloons-and-static-electricity#436. Here are my review notes:

- Higher level:
  - Why did you opt for a pattern that modifies a node like a mixin rather than just a straight mixin?Presumably it is so that this could be extended since mixins can't. But if feels odd that a class would mutate a Node like this. Is it a necessity to subclass GrabDragInteraction?

  - Is onDraggable necessary? Can you provide an example where onDraggable would be called where onDrag is not called? Or when you would want to use both?

  - FrictionGrabDragInteraction has a custom successfulDrag function. Something very similar is done in BASE now, could that function implementation be moved right into GrabDRagInteraction? Instead of "successfulDrag" when the positionProperty is not equal to the initial value, should we track key presses so that keyboard cues show up 

- Lower level:
  - I can't think of a case where we want the a11y options like tagName, ariaRole, and focusable to be changeable, OK if we move these out of options?

  - I don't understand these linese yet. FocusOverlay uses TransformTracker for transformations up the trail, will that be sufficient since the cues are added as children to the focus highlights? Why do we need to prepend nodes matrix?
```js
      // TODO: Likely we will need to monitor the parent for changes, and update accordingly, though for now it works in friction, see https://github.com/phetsims/scenery-phet/issues/421
      this.grabCueNode.prependMatrix( node.getMatrix() );
      this.grabFocusHighlight.addChild( this.grabCueNode );
      if ( this.dragCueNode ) {
        this.dragCueNode.prependMatrix( node.getMatrix() );
        this.dragFocusHighlight.addChild( this.dragCueNode );
      }
```

  - Would you mind if we rename thingToGrab option to something more descriptive, like objectToGrabString?

**Comment by jessegreenberg** [comment]
> I don't understand these linese yet....Why do we need to prepend nodes matrix?

I think I understand now. The pink `FocusHighlightFromNode` surrounds the node's **local** bounds, but is added to the global coordinate frame in `FocusOverlay`. So likewise, the cue nodes (or children added to the focus highlights) need to be transformed by the node's local transformation matrix to be positioned correctly when transformed by the node's `localToGlobalMatrix` in `FocusOverlay.update()`.

**Comment by zepumph** [comment]
>I think I understand now. The pink FocusHighlightFromNode surrounds the node's local bounds, but is added to the global coordinate frame in FocusOverlay. So likewise, the cue nodes (or children added to the focus highlights) need to be transformed by the node's local transformation matrix to be positioned correctly when transformed by the node's localToGlobalMatrix in FocusOverlay.update().

Yes this is less than ideal, and it was the cause of https://github.com/phetsims/friction/issues/181. I would love to find a different solution that was more robust.

**Comment by zepumph** [comment]
@jessegreenberg this fell off and I think should get cleaned up. Do you have a recommendation for how to proceed with the matrix manipulation?

**Comment by pixelzoom** [comment]
@jessegreenberg @zepumph  No forward progress in 13 months.  How do we wrap this up?

**Comment by zepumph** [comment]
We haven't run into trouble with transforming the cue Node thus far (with 4 production usages). Perhaps we can work on it if we every run into trouble. Presumably it would be very obvious when the matrix is off (I'm sorta shrugging over here).

**Comment by pixelzoom** [comment]
Reviewing scenery-phet issues for Q4 planning... 

This issues seems to have problems wrapping up. It's 3+ years old, and I'm growing weary of having to manage other people's work. @jessegreenberg @zepumph @kathy-phet.

**Comment by jessegreenberg** [comment]
The remaining work in this issue was to improve the transforms for the focus highlights but we haven't had time to do that. Lets close this issue and make a new one just for that but it will probably be low priority. See https://github.com/phetsims/scenery-phet/issues/775. @zepumph is that OK with you?

**Comment by zepumph** [comment]
Sounds great!
