### ISSUE TITLE
revise and use energy colors in PhetColorScheme

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#456]
In https://github.com/phetsims/scenery-phet/issues/455, I discovered sims are not using common-code colors for energy.   See:
ESP: https://github.com/phetsims/energy-skate-park/issues/51
MAS: https://github.com/phetsims/masses-and-springs/issues/343
Pendulum Lab: https://github.com/phetsims/pendulum-lab/issues/209

.. and there may be others. 

I pointed out that they should be using PhetColorScheme.  @arouinfar said in https://github.com/phetsims/scenery-phet/issues/455#issuecomment-452513073:

> @pixelzoom I would argue that some of the colors used for energy in PhetColorScheme are antiquated. 
> 
> To be clear, I think that energy colors should be consistent across sims, so it's great to point out these inconsistencies. However, using `rgb(0, 0, 255)` for gravitational potential energy and `rgb(236, 153, 55)` for total energy are definitely legacy artifacts.

So this issue has two goals:

(1) Revise energy colors in [PhetColorScheme](https://github.com/phetsims/scenery-phet/blob/master/js/PhetColorScheme.js).  These colors were specified in https://docs.google.com/spreadsheets/d/1mNsOWSbcoO-Ox2evxJij5Lix4HTZbXKbFgMlPe9W-u0/edit#gid=0

(2) Use PhetColorScheme in sims that use energy-related color coding.

**Comment by arouinfar** [comment]
Thanks for opening this issue @pixelzoom. I'll dig in more tomorrow.

>... and there may be others.

The only other sim that comes to mind is Hooke's Law, which has elastic energy. I've opened the above issue in the hookes-law repo.

**Comment by pixelzoom** [comment]
I confirmed that the only color that is incorrectly ported is PhetColorScheme.ELASTIC_ENERGY.  Correcting that will be handled in https://github.com/phetsims/hookes-law/issues/70.

**Comment by arouinfar** [comment]
Here are my suggested changes @pixelzoom.

| Energy | Current [PhetColorScheme](https://github.com/phetsims/scenery-phet/blob/master/js/PhetColorScheme.js) | Proposed Color |
| --- | --- | --- |
| `ELASTIC_POTENTIAL_ENERGY` | `rgb( 0, 204, 255 )` |  no change |
| `GRAVITATIONAL_POTENTIAL_ENERGY` | `rgb( 0, 0, 255 )`, BLUE | `rgb( 55, 130, 215 )` |
| `HEAT_THERMAL_ENERGY` |`rgb( 255, 85, 0 )`, RED_COLORBLIND | no change |
| `KINETIC_ENERGY` | `rgb( 0, 255, 0 )`, GREEN | `rgb( 30, 200, 45 )` |
| `TOTAL_ENERGY` | `rgb( 236, 153, 55 )` | `rgb( 180, 180, 0)` |

I think Pendulum Lab tends to have higher contrast in the colorblind preview modes, so I decided to use its definitions for GPE and KE, with rgb values rounded to the nearest 5. This results in a nicer-looking rgb value, but doesn't perceptibly change the color or relative contrast in colorblind preview modes. Since ESPB is the only sim which uses a solid total bar, I decided to keep its definition for `TOTAL_ENERGY`, albeit converted from hex to rgb.

| Colorblind preview | ESPB | MAS | PL |
| --- | --- | --- | --- |
| Protanopia | <img src="https://user-images.githubusercontent.com/8419308/50922504-e755d780-1407-11e9-904c-5b71029062c1.png" width=150> | <img src="https://user-images.githubusercontent.com/8419308/50922543-05233c80-1408-11e9-95bd-11919fabcfdf.png" width=150> |  <img src="https://user-images.githubusercontent.com/8419308/50922584-1d935700-1408-11e9-96e5-3b0b413ede8c.png" width=150> |
| Deuteranopia | <img src="https://user-images.githubusercontent.com/8419308/50922780-8c70b000-1408-11e9-8986-625f687ff8b7.png" width=150> | <img src="https://user-images.githubusercontent.com/8419308/50922918-df4a6780-1408-11e9-89d5-f17d4996a7cd.png" width=150> | <img src="https://user-images.githubusercontent.com/8419308/50922876-c641b680-1408-11e9-9541-b623552b2ccc.png" width=150> |

**Comment by pixelzoom** [comment]
@arouinfar said:
> Here are my suggested changes  ...

Thanks @arouinfar.  You said "suggested changes". Shall I go ahead and make these changes, or do you need to run this by other designers?

**Comment by arouinfar** [comment]
> You said "suggested changes". Shall I go ahead and make these changes, or do you need to run this by other designers?

Mostly so it didn't sound like I was barking orders, but thanks for checking @pixelzoom. Please go ahead and make the changes. Given that the HTML5 sims used similar shades of green and blue, I don't think this is a drastic change that would require  broader discussion. I'm also the lead/responsible designer for all of the sims that would be affected by such a change.

**Comment by pixelzoom** [comment]
👍 Woof woof :)

**Comment by arouinfar** [comment]
@pixelzoom I'm not sure that we would want `APPLIED_FORCE` and `TOTAL_ENERGY` to be color-coordinated, so I would recommend that we leave `APPLIED_FORCE` alone for now.

**Comment by pixelzoom** [comment]
Here are the changes to PhetColorScheme.  APPLIED_FORCE is unchanged, but no longer uses shared color TAN_ORANGE.

```js
APPLIED_FORCE: new Color( 236, 153, 55 ),
GRAVITATIONAL_POTENTIAL_ENERGY: new Color(  55, 130, 215 ),
KINETIC_ENERGY: new Color( 30, 200, 45 ),
TOTAL_ENERGY: new Color( 180, 180, 0 ),
```

Closing.
