### ISSUE TITLE
Change StepButton constructor?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#466]
Related to https://github.com/phetsims/wave-interference/issues/342.

Compare `PlayButton` and `StepButton` constructor APIs:

```js
function PlayPauseButton( isPlayingProperty, options )

function StepButton( options ) {

    options = _.extend( {
      ...
      // {Property.<boolean>|null} is the sim playing? This is a convenience option.
      // If this Property is provided, it will disable the button while the sim is playing,
      // and you should avoid using the button's native 'enabled' property.
      isPlayingProperty: null,
      ...
    }, options );
} 
```

Why are they different?  Should `isPlayingProperty` be a required parameter for `StepButton`? 

The only clients now are wave-interference and gas-properties, so this would be a good time to change.  

@samreid your opinion?

**Comment by pixelzoom** [comment]
Hmm... StepForwardButton extends StepButton, and is used by many sims, so this change would be more involved than expected. 

Also wondering if wave-interference and gas-properties should be using StepForwardButton?

**Comment by pixelzoom** [comment]
Oh my. StepForwardButton and StepBackwardButton totally fail if you don't pass them options. I'll fix that in the next commit.

**Comment by samreid** [comment]
To me, it makes sense that `PlayPauseButton` requires `isPlayingProperty` since it has direct control over it.  I skimmed through every occurrence of `StepForwardButton` and `StepBackwardButton` and found they all use `isPlayingProperty` (aside from demo usages).

I can imagine we may want to repurpose `StepForwardButton` or `StepBackwardButton` to leave it always enabled (and not wired up to a property), but perhaps in those cases (if they come up) we would just pass `new StepForwardButton(new BooleanProperty(true),options)` or `new StepForwardButton(null,{})`.  But if we think we would support those cases, then would it be simpler to leave it as an option?  Or we could make it required for now and re-evaluate once we have our first case that doesn't want to supply a Property. 

@pixelzoom how do you recommend to proceed?

**Comment by pixelzoom** [comment]
Let's just leave it as is for now and forget that I brought it up :)

Closing.
