### ISSUE TITLE
NumberPicker has Properties that should not be instrumented

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#471]
Noted while working on Graphing Quadratics PhET-iO instrumentation, https://github.com/phetsims/graphing-quadratics/issues/112.

NumberPicker looks really complicated in Studio "All" mode. E.g. for the 'a' coefficient picker:

<img width="215" alt="screenshot_1101" src="https://user-images.githubusercontent.com/3046552/53674261-ee4fd800-3c49-11e9-91e4-d4b7f974278c.png">

This may be vestigial from the "instrument everything" period of PhET. I recommend that we drop instrumentation of these Properties, which are internal details:

upStateProperty 
downStateProperty
upEnabledProperty
downEnabledProperty

**Comment by zepumph** [comment]
That seems reasonable to me. There is no reason to expand an already complicated api until it is asked for. 

If a user wanted to know if the picker can be incremented more, then that should be done through the NumberProperty passed into the picker, and its associated range (so basically in the model instead of the view).

I'm in favor of picker having the following API:
* enabledProperty
* visibleProperty
* opacityProperty
* pickableProperty

**Comment by pixelzoom** [comment]
@samreid @zepumph are you aware of any sims or clients that are relying on upStateProperty. downStateProperty, upEnabledProperty, downEnabledProperty?  Is it safe for me to remove them?

**Comment by samreid** [comment]
I'm not aware of any usages.   Those 4 properties are either private or closure variables, and we have not published stable API simulations yet, so it is still safe to remove features like that.

**Comment by pixelzoom** [comment]
Instrumentation of internal Properties removed in the above commit.   Screenshot below shows an example, `graphingQuadratics.standardFormScreen.view.equationAccordionBox.interactiveEquationNode.aPicker`.  

@zepumph would you please review?

<img width="205" alt="screenshot_1102" src="https://user-images.githubusercontent.com/3046552/53769469-344eab00-3e99-11e9-8341-18e760fba713.png">

**Comment by zepumph** [comment]
Looks good to me!
