### ISSUE TITLE
ComboBoxDisplay layout problem

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#482]
ComboBoxDisplay appears to have an initial layout problem when its value exceeds its range.  Selecting another choice and then switching back fixes the layout, hence "initial".

The problem also might be in NumberDisplay (displays the dynamic value), ComboBox (superclass), ComboBoxButton, ComboBoxListBox, ...

E.g. in Gas Properties `PressureDisplay` with `range: new Range( 0, 99 )`:

![screenshot_128](https://user-images.githubusercontent.com/3046552/55439221-20ae6700-5561-11e9-8779-b12574485412.png)

**Comment by pixelzoom** [comment]
The problem also might be in NumberDisplay, which ComboBoxDisplay uses to display the value.

**Comment by pixelzoom** [comment]
There are other problems.  When the listbox is open, the highlighting is all wrong.  For example, in this screenshot the cursor is over the bottom item in the listbox.

![screenshot_130](https://user-images.githubusercontent.com/3046552/55439500-088b1780-5562-11e9-8967-30fe9a116261.png)

**Comment by pixelzoom** [comment]
I've worked around this in gas-properties by increasing the range provided to NumberDisplay.   So I'm decreasing the priority for addressing this.   Other users of ComboBoxDisplay (e.g. @jbphet states-of-matter) should be aware of this issue.

**Comment by jbphet** [comment]
Thanks for the heads up.  States of Matter doesn't support alternative units for pressure, it only uses atm, so at least for now I don't think this issue affects it.

**Comment by pixelzoom** [comment]
@jbphet I guess I was thinking of the thermometer in SOM.   But it looks like you haven't change to use ComboBoxDisplay yet in https://github.com/phetsims/states-of-matter/issues/236.

**Comment by pixelzoom** [comment]
Hmm....  This is still an issue in Gas Properties in some situations.  For example, if you put a couple of particles in the container and heat them up, you can exceed the range of the pressure gauge.  The correct pressure is displayed, but the formatting is a little off, see screenshot below.  I could add an additional digit to the pressure gauge to make this more difficult to happen, but it would be better to address this issue. 

<img width="1002" alt="screenshot_1214" src="https://user-images.githubusercontent.com/3046552/58392211-3175d900-7ff6-11e9-9ecd-5e1764014e0f.png">

**Comment by pixelzoom** [comment]
Here's an implementation of SCENERY_PHET/ComponentsScreenView `demoComboBoxDisplay` that can be used to reproduce the problem.

```js
  // Creates a demo for ComboBoxDisplay
  var demoComboBoxDisplay = function( layoutBounds ) {

    var sliderRange = new Range( 0, 1000 );
    var smallerRange = new Range( 0, 10 );
    var valueProperty = new NumberProperty( 0 );

    // slider to control temperature
    var kSlider = new VSlider( valueProperty, sliderRange );

    // which choice is selected
    var choiceProperty = new NumberProperty( 0 );

    // items in the ComboBoxDisplay
    var items = [
      { choice: 0, numberProperty: valueProperty, range: smallerRange, units: 'ft' },
      { choice: 1, numberProperty: valueProperty, range: smallerRange, units: 'm' }
    ];

    // parent for the ComboBoxDisplay's popup list
    var listParent = new Node();

    var display = new ComboBoxDisplay( items, choiceProperty, listParent, {
      xMargin: 10,
      yMargin: 8,
      numberDisplayOptions: { font: new PhetFont( 20 ) }
    } );

    // VSlider to left of ComboBoxDisplay
    var hBox = new HBox( {
      spacing: 25,
      children: [ kSlider, display ],
      center: layoutBounds.center
    } );

    return new Node( {
      children: [ hBox, listParent ]
    } );
  };
```

**Comment by pixelzoom** [comment]
In the above commits, I rewrote SCENERY_PHET/ComponentsScreenView `demoComboBoxDisplay` to exercise layout functionality.   This demonstrates the problem.

**Comment by pixelzoom** [comment]
The problem is that ComboBoxListBox is not equipped to deal with item Nodes whose bounds change.  This is going to require some significant changes, and might be a good place to use AlignGroup and AlignBox.

**Comment by pixelzoom** [comment]
In the above commits, I added dynamic layout of items in the listbox and button.   This is working nicely in scenery-phet demo.  

@ariel-phet please assign someone to review, which should be completed before Gas Properties starts QA process.

**Comment by pixelzoom** [comment]
@ariel-phet if you're looking for suggestion for a reviewer, @jessegreenberg did review of the recent rewrite of ComboBox and its components.

**Comment by ariel-phet** [comment]
@pixelzoom, unfortunately JG is unavailable currently. @zepumph can review but it will be on Thursday

**Comment by zepumph** [comment]
* >The lovechild of a ComboBox and a NumberDisplay.

  I could definitely see the passion written into the code.

* >      `itemNodeWrapper.on( 'bounds', () => { updateAlignment(); } );`
  
  can be simplified to `itemNodeWrapper.on( 'bounds', () => updateAlignment() );`

* The "range" Property in each item passed to the ComboBoxDisplay seems like its job is a bit more opaque now. There is no error when the value of the item goes past that. Really that range is a formatting layout thing now. If you don't want the text to scale, then making that range the same as the valueProperty's max is a great idea, but when the display range is much smaller, it seems like it is just failing gracefully. I guess I'm wondering why we don't just assert out if the value ever goes outside of the range, and then just make sure usages pass in the appropriate range? This is more of a design question, and I don't know the design constraints that are already being worked within. I just thought I'd mention that this seems strange.

* To help understand the work done a bit more, I made cats' `valueProperty` derived from the value of dogs. This helps me to illustrate what an "ideal" usage of this is (with dogs because the range for the display is the same as the range for the value), and then also the less ideal but graceful implementation that you added via cats (where it scales down when larger than 1000). 


Good work and thanks for the opportunity to review and learn about this.

**Comment by pixelzoom** [comment]
@zepumph 
> can be simplified to itemNodeWrapper.on( 'bounds', () => updateAlignment() );

The code hasn't looked like that since 5/30/19. @zepumph were you reviewing an older version of the code?  

> The "range" Property in each item passed to the ComboBoxDisplay seems like its job is a bit more opaque now.  ...

I agree with all of this.  But this design issue is rooted in NumberDisplay, not ComboBoxDisplay.   So I've created https://github.com/phetsims/scenery-phet/issues/504.

Back to @zepumph.

**Comment by zepumph** [comment]
>The above review was done on 6/6/19, and the code hasn't looked like that since 5/30/19. @zepumph were you reviewing an older version of the code?

Yeah sorry about that. I'm not sure what I was looking at as I went through the commits. I should have checked with master before making that review comment. Though eventually I did look at the commits in summation on master.

Back to you.

**Comment by pixelzoom** [comment]
Closing, since the only unaddressed feedback has been moved to #504 (NumberDisplay numberRange is confusing).
