### ISSUE TITLE
issues with GaugeNode

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#502]
Issues with GaugeNode that I've encountered in Gas Properties:

- [x] needle is behind the tick marks
- [x] no way to set `lineWidth` for needle
- [x] no way to set `stroke` for tick marks, and they are 'gray'

**Comment by pixelzoom** [comment]
Addressed in the above commits.  I added options `needleLineWidth`, `majorTickStroke`, and `minorTickStroke`, and preserved their original values as defaults.   And did `addChild( needle )` last, so that the needle is on top of the ticks. 

@ariel-phet please assign someone to review.

**Comment by samreid** [comment]
I'll take a look.

**Comment by samreid** [comment]
The commits look reasonable to me.  The flat options pattern was used instead of the composite options pattern, but that seems reasonable to keep things simple here.  I'll open up a side issue regarding the z-order of the needle, but I think this issue can be closed. I'll send it back to @pixelzoom in case there's anything else before closing.

**Comment by pixelzoom** [comment]
Thanks for the review, nothing else to do, closing.
