### ISSUE TITLE
But new SliderTrack creates an instance that is not usable (and will fail an assertion) until setValueToPositionFunction is called. 

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#506]
From #498 

> Generally we want new to create a fully-functional instance. But new SliderTrack creates an instance that is not usable (and will fail an assertion) until setValueToPositionFunction is called. SliderTrack used to have a valueToPosition option. I'm not clear on what it was removed, put presumably there was some problem. Investigate restoring this option, or some other way to avoid creating a non-functioning instance.

See other comments in #498 culminating in https://github.com/phetsims/scenery-phet/issues/498#issuecomment-500599165

**Comment by samreid** [comment]
Implemented and ready for review.

**Comment by pixelzoom** [comment]
I reviewed the commit, which seems to be based on the approach outlined in https://github.com/phetsims/scenery-phet/issues/498#issuecomment-500005571.   

But in https://github.com/phetsims/scenery-phet/issues/498#issuecomment-500010699, @samreid said "additionally need a way to update the range" so I was sort of expecting to see `{Property} rangeProperty` instead of `{Range} range`.    @samreid did you punt on dynamic range, or solve it a different way?

**Comment by samreid** [comment]
My apologies, I was conflating two issues.  It seem that Slider does not support a dynamic range, but it does support a dynamic `enabledRange`.  I followed this pattern in SliderTrack, which takes a `enabledRangeProperty` option.

**Comment by samreid** [comment]
Marking for https://github.com/phetsims/wave-interference/issues/408

**Comment by pixelzoom** [comment]
Got it, thanks for clarification.  Feel free to close if this is done.
