### ISSUE TITLE
Add wavelength slider overlays to highlight certain wavelengths

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#509]
From #498 

Add wavelength slider overlays to highlight certain wavelengths

**Comment by samreid** [comment]
@ariel-phet similar question as https://github.com/phetsims/scenery-phet/issues/508#issuecomment-502833285. Do you want to investigate a "highlight certain wavelengths" feature now before Wave Interference 2.0 goes into production, or as a separate issue when we are working on a sim with that feature?

**Comment by pixelzoom** [comment]
Is this motivated by the MOTHA requirement that I mentioned in https://github.com/phetsims/scenery-phet/issues/498#issuecomment-492386526?  

> ... Also keep in mind that a sim like MOTHA requires decoration of its WavelengthSlider with absorption wavelength indicators.

I'm not convinced MOTHA's requirement is something that is generally useful.  So I don't think we need to do this immediately, or perhaps at all.  As long as there's a way to decorate a track, which seems doable with the new SpectrumSliderTrack, et. al.

**Comment by pixelzoom** [comment]
To job my memory and demo MOTHA requirements, here's what the spectrum slider looks like with "Show absorption wavelengths" checked:

<img width="374" alt="screenshot_1258" src="https://user-images.githubusercontent.com/3046552/59647132-4ba76080-9137-11e9-8f43-0a0aff21b5ee.png">

And when the thumb is positioned at one of the absorption wavelengths, note that the thumb stroke changes to 'white' to highlight it:

<img width="372" alt="screenshot_1259" src="https://user-images.githubusercontent.com/3046552/59647158-611c8a80-9137-11e9-90b0-a91de9c2a901.png">

Imo I never found this to be a particularly appealing way of indicating absorption wavelengths, because they are all bunched up at the left end of the track.  But I haven't had a better design suggestion.

**Comment by samreid** [comment]
> Is this motivated by the MOTHA requirement that I mentioned in #498 (comment)?

Yes, precisely.  I agree that the existing design is amenable to decoration in the future and believe this issue can be closed.  @ariel-phet or @pixelzoom feel free to reopen if you disagree.
