### ISSUE TITLE
TemperatureAndColorSensorNode from EFAC should be moved to scenery-phet

### ISSUE THREAD

**Issue by arnabp** [phetsims/scenery-phet#523]
The `TemperatureAndColorSensorNode` which is used in [energy-forms-and-changes](https://github.com/phetsims/energy-forms-and-changes) is also being used in [number-line-integers](https://github.com/phetsims/number-line-integers) and so should be moved to common code.

**Comment by arnabp** [comment]
Added TemperatureAndColorSensorNode to scenery-phet, assigning @jbphet for review

**Comment by jbphet** [comment]
Two suggestions:
+ Pass in a color property instead of having a method.  It seems inconsistent to pass in a property for one of the attributes displayed (temperature) and set the other via a method (color).  This may have been done to make it easier to use a fixed, unchanging color, but none of the current use cases do this and it would be easy enough to create an unchanging property if such a need arose.
+ Use a range for the temperature.  I know this isn't what's done for the thermometer node itself, but I think that may be because it predated the existence of the range class.

**Comment by arnabp** [comment]
Implemented both suggested changes. I noticed that EFAC had some extra property linking for setting the color to a default when the thermometer was disabled. Just setting a simple link to the colorProperty seems to be okay to me, but if you know the specific case for which that extra bit of code was added it would be good to spot check.

**Comment by jbphet** [comment]
I made some minor documentation changes, and tested the behavior on EFAC, and all of it looks good to me.  Closing.
