### ISSUE TITLE
MeasuringTapeNode should be updated to use the newer nested options pattern

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#529]
From https://github.com/phetsims/wave-interference/issues/431

MeasuringTapeNode has:

```js
    options = _.extend( {
      
      // ...
      textColor: 'white', // color of the length measurement and unit
      textBackgroundColor: null, // {Color|string|null} fill color of the text background
      textBackgroundXMargin: 4,
      textBackgroundYMargin: 2,
      textBackgroundCornerRadius: 2,
      textMaxWidth: 200,
```

This should be upgraded to use our nested options pattern.

**Comment by pixelzoom** [comment]
The options in the above comment are not suitable for nested options.  Only 2 of them are relevant to Text (textColor, textMaxWidth), 2 are relevant to a Rectangle (textBackgroundColor, textBackgroundCornerRadius), and 2 are used in a computation to size the Rectange (textBackgroundXMargin, textBackgroundYMargin).

So until more control is needed over some subcomponent of MeasuringTapeNode, I think it's fine to have a handful of top-level options, rather than exposing the internal structure of MeasuringTapeNode.

Closing.
