### ISSUE TITLE
Lines in faucet

### ISSUE THREAD

**Issue by ghost** [phetsims/scenery-phet#534]
**Test Device**

MacBook Air

**Operating System**

macOS 10.14.6

**Browser**

Safari 12.1.2

**Problem Description**

For https://github.com/phetsims/QA/issues/426. Upon loading the sim in Safari, there are lines in the faucet. Sometimes it's just the vertical line. Zooming in will usually make the line(s) go away.

**Visuals**

![issue](https://user-images.githubusercontent.com/31285590/65083175-0f1d1800-d965-11e9-82d7-550342114037.png)

<details>
<summary><b>Troubleshooting Information</b></summary>
!!!!! DO NOT EDIT !!!!!
Name: ‪Waves Intro‬
URL: https://phet-dev.colorado.edu/html/waves-intro/1.0.0-rc.5/phet/waves-intro_all_phet.html
Version: 1.0.0-rc.5 2019-09-13 04:12:55 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/12.1.2 Safari/605.1.15
Language: en-US
Window: 1440x837
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.20)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 16)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
I don't see this in the latested versions of Safari or Chrome on macOS 11.2.   It probably appears on some OS and some browser.  But FaucetNode is built from multiple Nodes, and there's already overlap built into those Nodes.   As @ariel-phet noted about, this is a very low priority issue.  And I seriously doubt that we would do something like reimplement FaucetNode as one Shape simply to get rid of these lines. 

So since this has been open for 17 months and has already used more resources than was probably intended, I'm going to close this as "won't fix".
