### ISSUE TITLE
Move the capacitor view from capacitor-lab-basics to scenery-phet

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#537]
From https://github.com/phetsims/circuit-construction-kit-common/issues/452, we would like to reuse the capacitor rendering code in Circuit Construction Kit.  I'll factor it out.  It's not clear how much of the model may need to be moved.  We should also create an isolated test harness for it.

**Comment by samreid** [comment]
@zepumph published a reference version before any work began:
https://phet-dev.colorado.edu/html/capacitor-lab-basics/1.8.0-dev.2/phet/capacitor-lab-basics_en_phet.html

**Comment by samreid** [comment]
The main port is complete, and a demo has been added to the scenery-phet harness.  I'll continue by converting to ES6 and performing a code review.

**Comment by samreid** [comment]
Tagging for https://github.com/phetsims/circuit-construction-kit-common/issues/528

**Comment by samreid** [comment]
The main part of this work is complete and can be reviewed.  There are still other steps to be taken in https://github.com/phetsims/scenery-phet/issues/555, but that will be done separately.  @ariel-phet can you please assign a reviewer?  @Denz1994 may be a good match since this code is also used in Capacitor Lab Basics.

**Comment by ariel-phet** [comment]
@Denz1994 over to you -- this review would be fairly high priority as we are attempting to keep momentum on CCK: AC

**Comment by Denz1994** [comment]
@samreid I added some review comments annotated with `REVIEW:`. Most of them are doc updates, but the demo in scenery-phet doesn't update the display for the separation and charge values. The property values are updating, so I suspect this has to do with the range of values we are displaying for the `NumberControl` in `ComponentsScreenView.js`. 

I will leave for you to investigate, but otherwise, my comments are noted in the documentation.

**Comment by samreid** [comment]
Thanks for reviewing this @Denz1994.

> // REVIEW: this.topNode.shape is mutated below, is this still a read-only?

My understanding is that (read-only) refers to how clients may use it, not how it is used internally.

> REVIEW: Is this documenation supposed to be used to track this file's history on github? If so, please ignore.

I think we agreed that as long as the information is in one commit message or one commit, that is sufficient.  I'll remove it.

I also addressed other //REVIEW comments in the commits.  Back to you @Denz1994.

**Comment by Denz1994** [comment]
`REVIEW` comments have been addressed and the slider in the demo is updating the value.

One further recommendation @samreid : Could you pass in `SeparationProperty` and `PlateChargeProperty` with a scale factor. I'm only recommending this because the actual values are on the order of and 10^-3 and 10^-13 respectively and it causes the readout to expand awkwardly. Alternatively, we could add a unit string to indicate why there are so many significant figures. 

I'll leave it to you if you want to pursue this further, otherwise, I'll assign it to you to close this issue.

**Comment by samreid** [comment]
There is an issue for converting to use view-oriented units: https://github.com/phetsims/scenery-phet/issues/555.  I think that would cover the change above.  I'll make a note there and close this issue.  Thanks @Denz1994!
