### ISSUE TITLE
Keypad should use nested options for its NumberAccumulator

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#541]
Discovered while working on https://github.com/phetsims/scenery-phet/issues/540. Tagging @Denz1994 to see what he thinks.

**Comment by zepumph** [comment]
Right now I have to omit the parent tandem before passing in the child one:

```js
    // @private {function}
    this.keyAccumulator = options.accumulator ? options.accumulator : new NumberAccumulator( merge( {
      tandem: options.tandem.createTandem( 'numberAccumulator' )
    }, _.omit( options, 'tandem' ) );
```

**Comment by pixelzoom** [comment]
I don't see any opportunities for using nested options in NumberAccumulator.

@zepumph Do you mean that KeyPad should use nested options for its NumberAccumulator subcomponent?

**Comment by pixelzoom** [comment]
I'm going to work on this issue, self assigning.

**Comment by pixelzoom** [comment]
There are 13 occurrences of `import Keypad` to be inspected for use of NumberAccumulator options.

**Comment by pixelzoom** [comment]
Options `accumulatorOptions` was added to Keypad in the above commit, and adjustments were made to sims. area-model-common required no adjustments because it provides `options.accumulator` to Keypad, therefore making `options.accumulatorOptions` irrelevant.  

In additon to testing all sims that use Keypad, I inspected the Studio tree in projectile-motion (screenshot below) and it looks correct. 

@zepumph would you mind doing a quick review, since you created this issue?

<img width="1123" alt="screenshot_881" src="https://user-images.githubusercontent.com/3046552/108892258-e58e0480-75cc-11eb-8ffa-cdfa87731c8f.png">

**Comment by zepumph** [comment]
Looks really nice. Thanks
