### ISSUE TITLE
NumberControl option to exclude arrow buttons

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#549]
From https://github.com/phetsims/projectile-motion/issues/197, there are currently layoutFunctions that support excluding the tweakers, but for PhET-iO this is incomplete. I think that it would be better to not create them at all. 

After discussing with @samreid and poking around a bit, it turned out to not be a very invasive change.

**Comment by zepumph** [comment]
I added an option above, and called it `excludeTweakers`, paralleling the option in `layoutFunction4`. I then removed support for that, and make those usages use the NumberControl options. @pixelzoom will you please review this change?

**Comment by pixelzoom** [comment]
I reviewed the commits.  I understand why you renamed the option `excludeTweakers`.  But I think your first instinct, to name it `includeArrowButtons`, was the correct choice. It's more consistent with both the API and implementation -- option `arrowButtonOptions` (not tweakerOptions) is part of the API, and the buttons are `ArrowButtons` (not TweakerButtons, which don't exist).  I'm also not a fan of options that specify whether to "exclude", I much prefer "include" (similar to disable vs enable, invisible vs visible, and other boolean states).

I'll also point out that we've encountered situations where NumberControl's title is also undesired -- most recently in gas-properties (see `temperatureLayoutFunction` in `InjectionTemperatureAccordionBox`) and another case that I recall @samreid asking about not too long ago, where I think he used a similar custom `layoutFunction`.  These cases will presumably have a similar PhET-iO issue, so should we handle it similarly? It will be more complicated, since it involves changing `NumberControl`'s constructor signature -- `{string} title` is a required constructor parameter, and would need to move to options.

It looks like `energy-skate-park/PhysicalNumberControl` has a `layoutFunction` that conditionally hides tweakers (sic) and `NumberDisplay`.  So should we also deal with making the `NumberDisplay` optional, via an additional `includeNumberDisplay` option? 

I'm also starting to wonder...  `NumberControl` was not original specified or implemented to have optional subcomponents, and there was a goal of unifying the approach for this type of control (there were a lot of similar implementations with insignificant/unintentional differences).  First that diverged with the introduction of `layoutFunction`.  Now it's diverging further.  Have we lost sight of the original goals? Do we really need so many variations? Are subjective requirements creeping in that might change if designers knew what the limitations of NumberControl are? 

Back to @zepumph.

**Comment by pixelzoom** [comment]
Thoughts on my previous comment...

I'd like to see the option renamed to `includeArrowButtons: true`, otherwise I think this specific issue is addressed nicely.

I think it would be fine to address optional title and NumberDisplay in new issue(s). 

Reflection on `NumberControl` probably warrants a design discussion.

**Comment by zepumph** [comment]
>I'd like to see the option renamed to includeArrowButtons: true, otherwise I think this specific issue is addressed nicely.

Good idea. Done in the above commit. 


I created new issues, though I don't know how to assign or prioritize them.

Closing.
