### ISSUE TITLE
Keypad entry

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/scenery-phet#55]
This issue will track issues surrounding keypad entry

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/area-builder/issues/46, Keypad was migrated to common code. Does it meet all of the above functionality requirements?

**Comment by jbphet** [comment]
A common code version of a number keypad has been added to the scenery-phet repo, see https://github.com/phetsims/scenery-phet/blob/master/js/NumberKeypad.js and issue https://github.com/phetsims/area-builder/issues/46.  This component is currently used in Area Builder and Arithmetic, and will soon be used in Making Tens as well.  So far there hasn't been a need for the decimal or sign entry capabilities described above, and the current implementation does not support these features.  To my knowledge, there are no sims on the immediate horizon that need decimal or sign entry.

I will assign this issue to @ariel-phet to determine whether we should add these capabilities now or wait until they are needed.  If and when the additional capabilities are needed, we might want to split out a simple version for entry of positive integers and a more sophisticated version for entry of signed and decimal numbers instead of trying to control everything through options, but we can cross that bridge when we come to it.

**Comment by ariel-phet** [comment]
This work can wait. Closing this issue, we can make an issue for these features if/when it becomes necessary.
