### ISSUE TITLE
HeaterCoolerNode passes the same tandem to 2 Nodes

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#579]
Encountered while instrumenting Gas Properties in https://github.com/phetsims/gas-properties/issues/147.

There's a bug in PhET-iO instrumentation of HeaterCoolerNode.

Here's the relevant code in HeaterCoolerNode.js:

```js
      options = merge( {
...
        tandem: Tandem.REQUIRED
      }, options );

      const heaterCoolerFront = new HeaterCoolerFront( heatCoolAmountProperty, merge( {
...
        // The front takes the entire tandem since we are treating it as a consolidated component (client doesn't need
        // to know about front vs back)
        tandem: options.tandem
      }, options.frontOptions ) );
...
     super.mutate( options );
```

`options.tandem` is being passed to both `new HeaterCoolerFront` and `super.mutate`.  

For http://localhost/~cmalley/GitHub/studio/?sim=gas-properties&phetioValidateTandems&phetioDebug&phetioElementsDisplay=all, this will fail with with:

> main.js:109 Uncaught Error: Assertion failed: phetioID already registered: gasProperties.idealScreen.view.heaterCoolerNode.visibleProperty

Commit history shows that this problem was introduced in https://github.com/phetsims/scenery-phet/commit/95bc40545dec394200f07b33bd4e334feae60532, so assigning to @samreid.

**Comment by pixelzoom** [comment]
I'm going to assign this to @chrisklus too, since he recently did work on HeaterCoolerNode.  

Thoughts on how we should address this issue?  Some options that come to mind:

(a) Pass `options.tandem` to `HeaterCoolerFront`, don't propagate `options.tandem` to `HeaterCoolerFront ` super.   This would make `HeaterCoolerFront` children look like children of `HeaterCoolerNode` in the tandem hierarchy. 

(b) Pass `options.tandem.createTandem( 'front' ) to `HeaterCoolerFront`.  This exposes structure that we may have been trying to hide.

**Comment by pixelzoom** [comment]
I went with option (a).  

Here's how it's handled in `HeaterCoolerFront`:

```js
 this.mutate( merge( {}, options, {

      // Do not propagate options.tandem to super, because we want to hide the specifics of HeaterCoolerFront.
      // See https://github.com/phetsims/scenery-phet/issues/579
      tandem: Tandem.OPTIONAL
    } ) );
```

Here's how it looks in Studio for gas-properties:

<img width="228" alt="screenshot_163" src="https://user-images.githubusercontent.com/3046552/75813571-6f561980-5d4d-11ea-9d73-33d3781342ac.png">

@samreid or @chrisklus please review in master.

**Comment by samreid** [comment]
@chrisklus can you please review this?  It has usage in Energy Forms and Changes and you are probably more familiar with HeaterCoolerNode than I.

**Comment by chrisklus** [comment]
Thanks for finding and addressing this @pixelzoom, and sorry for the delay.

Nice idea! The current fix doesn't work for cases that use HeaterCoolerFront and HeaterCoolerBack separately because HeaterCoolerFront doesn't get its NodeIO Properties in Studio. But I just moved your pattern to HeaterCoolerNode instead of HeaterCoolerFront, and both types of usages appear to be correct. HeaterCoolerFront is really the only thing that's instrumented, as it's creating the illusion of one Node by driving the NodeIO Properties of HeaterCoolerBack. So it makes sense to me that its parent should not pass a Tandem to super since we're hiding their relationship.

My recommendation was going to be to revert to the api outlined in https://github.com/phetsims/scenery-phet/issues/568#issuecomment-569442934 (omit Tandem from HeaterCoolerNode entirely), but your solution is a bit friendlier to phet developers.

What do you think?

**Comment by pixelzoom** [comment]
Reviewed with @chrisklus on Zoom.  Looking good! Closing.
