### ISSUE TITLE
TimeControlNode API Review

### ISSUE THREAD

**Issue by Denz1994** [phetsims/scenery-phet#607]
Related to:https://github.com/phetsims/scenery-phet/issues/604#issuecomment-630309199

**TimeControlNode.js**

- [x] `options.timeSpeeds` has type doc that reads `TimeSpeed[]`. Alternatively, there are type docs (by other devs) that follow the format `Array.<TimeSpeed>`. If this format is up to developer discretion, then leave as is. I wasn't sure, so I'm making a note.

- [x] The type doc for `timeSpeedProperty` reads `{null|EnumerationProperty.<TimeSpeed>}`. I would swap the ordering to read `{EnumerationProperty.<TimeSpeed>|null}` to be consistent with the other type docs in `options`.

**TimeSpeed.js**

- [x] Update author tag to include `* @author Chris Malley (PixelZoom, Inc.)`

**Studio**
- [x] When viewed from Studio*, `timeSpeedProperty` shows `"validValues": [ "FAST", "NORMAL", "SLOW" ] ` but the radio buttons only include normal and slow options. Selecting the "FAST" option in Studio does nothing as far as I can tell. Is this behavior intended or related to a separate issue?
*Found in: Molecules and Light, Projectile Motion, ESP, WOAS

The points in `TimeControlNode.js` aren't direct changes from @pixelzoom's commits but are closely related, so I mentioned them above. I see no more usages of "TimeControlSpeed" or any of the variants mentioned in https://github.com/phetsims/scenery-phet/issues/604#issue-618503486 and the sims affected work with their respective TimeControl implementations.

Turning over to @pixelzoom for feedback.

**Comment by Denz1994** [comment]
Regarding the Studio point above. WOAS has an assertion to prevent a "FAST" value (see `WOASModel.manualStep`). It seems like there is some discontinuity between what the sim accepts as a valid value and what Studio represents as a valid value. 

I would expect Studio to not show "FAST" but I'm not sure what the level of implementation that would require.

**Comment by Denz1994** [comment]
More specifically, the WOAS assertion mentioned above will prevent any values that aren't "NORMAL" or "SLOW".

**Comment by pixelzoom** [comment]
> **TimeControlNode.js**
> 
> - [x] `options.timeSpeeds` has type doc that reads `TimeSpeed[]`. Alternatively, there are type docs (by other devs) that follow the format `Array.<TimeSpeed>`. If this format is up to developer discretion, then leave as is. I wasn't sure, so I'm making a note.

`TimeSpeed[]` and `Array.<TimeSpeed>` are  equivalent, see https://jsdoc.app/tags-type.html: "You can also indicate an array by appending [] to the type that is contained in the array. For example, the expression string[] indicates an array of strings."  I prefer the former, and I believe that we left this up to developer discretion.  If you think it's something that should be standardized, feel free to open up an issue.

> - [x] The type doc for `timeSpeedProperty` reads `{null|EnumerationProperty.<TimeSpeed>}`. I would swap the ordering to read `{EnumerationProperty.<TimeSpeed>|null}` to be consistent with the other type docs in `options`.

Done in above commit.

> **TimeSpeed.js**
> 
> - [x] Update author tag to include `* @author Chris Malley (PixelZoom, Inc.)`

Done in above commit.

> **Studio**
> - [ ] When viewed from Studio*, `timeSpeedProperty` shows `"validValues": [ "FAST", "NORMAL", "SLOW" ] ` but the radio buttons only include normal and slow options. Selecting the "FAST" option in Studio does nothing as far as I can tell. Is this behavior intended or related to a separate issue?
> *Found in: Molecules and Light, Projectile Motion, ESP, WOAS

The problem is in the client (sim) code. They are defining their `timeSpeedProperty` incorrectly.  For example, Molecules and Light defines `timeSpeedProperty` like this in 

```js
  // @public {EnumerationProperty.<TimeSpeed>} - controls play speed of the simulation
  this.timeSpeedProperty = new EnumerationProperty( TimeSpeed, TimeSpeed.NORMAL, {
    tandem: tandem.createTandem( 'timeSpeedProperty' )
  } );
```

By default, EnumerationProperty is going to consider all values of the Enumeration (in this case, TimeSpeed) to be valid.  EnumerationProperty, line 41:

```js
      validValues: enumeration.VALUES // for PhET-iO documentation and support
```

In general, it's OK to have an EnumerationProperty that supports a subset of an Enumeration, and I'd expect that to become more common as Enumerations find there way into common code.  In this case, if NORMAL and SLOW are the only speeds supported, then the client must specify that via `validValues`:

```js
  // @public {EnumerationProperty.<TimeSpeed>} - controls play speed of the simulation
  this.timeSpeedProperty = new EnumerationProperty( TimeSpeed, TimeSpeed.NORMAL, {
    tandem: tandem.createTandem( 'timeSpeedProperty' ),
    validValues: [ TimeSpeed.NORMAL, TimeSpeed.SLOW ]
  } );
```

That results in the desired behavior in Studio:

<img width="599" alt="screenshot_333" src="https://user-images.githubusercontent.com/3046552/82941950-79ef0c00-9f54-11ea-9cb5-73850dfc489c.png">

Recommended to create issues in Molecules and Light, Projectile Motion, ESP, WOAS. Would you mind handling that @Denz1994?

**Comment by Denz1994** [comment]
Issues have been opened above. I'll close this one since there is nothing left to do here.
