### ISSUE TITLE
Should stopwatch go beyond the max time, and/or display time differently?

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#617]
In https://github.com/phetsims/scenery-phet/issues/565

I said:

> Now that it is trivial to allow the stopwatch to go beyond 59:59.00 and have it scale down, will we want to prefer that in the design? Will we want to change that for any of the sims mentioned above?

@pixelzoom replied:

>  I've opened phetsims/gas-properties#188 to review the use of new features in Gas Properties. Recommended to do the same for other sims, or at least notify the designers that these options are now available.

Here are some sims that currently stop the stopwatch at a specific time:

```
capacitor lab: 	        pauses at 59:59.99.  fixed
cck: 	                not published, allowing to go past 59:59.99 and scale down until design finalized
esp: 	                pauses at 59:59.99. fixed
gas-properties:      pauses at 999.99 ps.  fixed
masses-and-springs:	pauses at 59:59.99. fixed
pendulum-lab:         pauses at 59:59.99. fixed
wave-interference:	pauses at 999.99.  fixed
wave-on-a-string:	pauses at 59:59.99. fixed
```

I'll assign some designers to ask whether any or all of these change be changed to continue counting and scale down, or if we should leave them as they are--stopping at their specified maximum.  @ariel-phet and @arouinfar please take a look and recommend how to proceed, and please assign other designers or open side issues as necessary.

**Comment by pixelzoom** [comment]
The stopwatch does not pause, it stops --- pause implies it can be started again and continue for the stopped point.

The other issue to be considered is the number of decimal places in the display.  For example, in Gas Properties we had to settle for 2 decimal places, when 1 would have been more desirable.

Changing the title of this issue to reflect this.

**Comment by ariel-phet** [comment]
@samreid @pixelzoom none of the sims listed above need to change stopping the stopwatch at a specified time. For all of those sims that basically stop before 1 hour, there is no pedagogically good reason to run longer, and stopping at some threshold is somewhat normal stopwatch behavior for "minutes:seconds.milliseconds" readout. I see no reason to change these as it has not been an issue. Certainly for future sims, we should consider the best behavior in each case, but the ones listed above are all fine. 

Closing

**Comment by pixelzoom** [comment]
Reopening.  

Whether the stopwatch should stop at a max time is half of the question.  The other issue is the time format (specially number of decimal place) and  I don't see anything related to that discussed here. For example, in phetsims/gas-properties#188 there's no pedagogical reason to show 2 decimals places, and it if we can avoid updating the display so often (for performance reasons) then we certainly should since this will be a PhET-iO sim.

**Comment by ariel-phet** [comment]
I think that is a question for @arouinfar -- for all the other sims on the list I think the decimal places are fine. I would be fine with gas properties going to 1 decimal place.

**Comment by pixelzoom** [comment]
Another general design issue is whether StopwatchNode's NumberDisplay should be PhET-iO instrumented.  The NumberDisplay subcomponent is instrumented in some other UI components (NumberSpinner, FineCoaserSpinner). That's currently not the case for StopwatchNode.  Yes, the client could instrument it via `numberDisplayOptions`, but not without having be responsible for making the tandem hierarchy look correct.  

>  for all the other sims on the list I think the decimal places are fine

That may be true for brand=phet. But if StopwatchNode's NumberDisplay is instrumented, then sims like ESP are going to be updating the NumberDisplay's `valueText` Property at a very high frequency.  That has PhET-iO implications.

**Comment by arouinfar** [comment]
In general, I don't see a lot of value in letting the stopwatch run indefinitely. I can take it or leave it.

In terms of decimal places, I'll need to evaluate it sim by sim to see if that level of precision is necessary for the learning goals. I'll review each sim, and if I think changes need to be made, I'll open an issue in the sim repo. If it turns out that 1 decimal place is acceptable in most sims, we should make that the default.

- [ ] Capacitor Lab: Basics
- [ ] CCK
- [ ] Energy Skate Park
- [X] Gas Properties - https://github.com/phetsims/gas-properties/issues/188
- [ ] Masses and Springs
- [ ] Pendulum Lab
- [ ] Wave Interference/Waves Intro
- [ ] Wave on a String

**Comment by arouinfar** [comment]
The appropriate number of decimal places really depends on the StepForwardButton time increment. If the increment needs to be < 0.1 s, the stopwatch display should have two decimal places. 

StepForwardButton increment:
* Capacitor Lab: Basics - 0.2 s
* Circuit Construction Kit: AC - 0.1 s
* Energy Skate Park -  0.02 s
* Gas Properties - 0.2 ps
* Masses and Springs (Basics) - 0.01 s
* Pendulum Lab - 0.01 s
* Wave Interference/Waves Intro - < 0.1, varies by scene (https://github.com/phetsims/wave-interference/issues/226#issuecomment-447593072)
* Wave on a String - 0.02 s

These time steps are all appropriate. Sims with smaller time steps have more dynamic action and the extra precision in the stopwatch display is necessary. Capacitor Lab: Basics and CCK: AC don't need two decimal places, so I've opened issues in those repos.

> Another general design issue is whether StopwatchNode's NumberDisplay should be PhET-iO instrumented. 

I don't think we'll need to instrument the NumberDisplay. Clients will need access to the time displayed on the StopwatchNode, but they can access that via `stopwatch.timeProperty`.

Since the remaining work is being tracked in sim repos, I'll close this issue.
