### ISSUE TITLE
StopwatchNode readout no longer respects selected units

### ISSUE THREAD

**Issue by samreid** [phetsims/scenery-phet#628]
From https://github.com/phetsims/collision-lab/issues/140, the stopwatch readout no longer changes when selecting different units:

![image](https://user-images.githubusercontent.com/679486/95102107-3372a080-06f0-11eb-972c-a425900c86d7.png)

@ariel-phet can you please prioritize and assign?  Is this likely to affect any upcoming publications?

**Comment by ariel-phet** [comment]
@pixelzoom can you take a look here - I am guessing this is a quick fix and given your recent review of StopwatchNode

**Comment by pixelzoom** [comment]
This is not a quick fix, and was apparently broken when StopwatchNode was refactored/rewritten.

In scenery-phet `ComponentsScreenView`, the value of `unitsProperty.value` (not the Property itself) is passed via the `numberFormatter` option:

```js
  const mutableUnitsStopwatchNode = new StopwatchNode( mutableUnitsStopwatch, {
    numberDisplayOptions: {
      numberFormatter: StopwatchNode.getRichNumberFormatter( {
        units: unitsProperty.value
      } )
    },
    scale: 2,
    tandem: options.tandem.createTandem( 'stopwatchNode' )
  } );
  unitsProperty.link( () => mutableUnitsStopwatchNode.redrawNumberDisplay() );
```

There's nothing in the API that supports dynamic units. So there's no way for StopwatchNode (or its subcomponents) to know that the units have changed.  I'm not sure of the best way to address this, since the predefined `numberFormatter` values are (a) complicated and (b) in need of significant work in https://github.com/phetsims/scenery-phet/issues/618.  

@samreid You did the recent rewrite of StopwatchNode. How do you suggest that we proceed?

**Comment by pixelzoom** [comment]
Labeling as blocking until we decide otherwise.

**Comment by samreid** [comment]
I committed a proposed fix which seems to be working well in testing.  Ready for review/testing.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/scenery-phet/issues/628#issuecomment-707274553, I said:
> I also can't tell if the old implementation of StopwatchNode supported dynamic units via a Property, or if this a new feature that is expected to work.

The above fix is specific to scenery-phet demo, and it not handled by StopwatchNode.  So does that mean that StopwatchNode is not expected to handle dynamic units?  If the answer is "yes", that's fine with me.  But the title of this issue ("StopwatchNode no longer respects selected units") seems to imply that dynamic units were once working and are now broken.

**Comment by samreid** [comment]
Yes, this was only fixed in the demo, but it provides an example of how to change the units for a StopwatchNode:

```js
    mutableUnitsStopwatchNode.numberDisplay.setNumberFormatter( StopwatchNode.getRichNumberFormatter( {
        units: unitsProperty.value
      } )
    );
```

Would you like that API to be improved before we close this issue?

**Comment by pixelzoom** [comment]
Slack:
> Chris Malley  9:41 AM
To clarify for https://github.com/phetsims/scenery-phet/issues/628...  StopwatchNode did not previously support dynamic units, correct?
>
> Sam Reid  9:41 AM
Not directly, no.

Then I'm fine with just closing this. If that feature becomes a common needed, we can add it later via a new issue.
