### ISSUE TITLE
NumberPicker should have a callback on input

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#646]
@jessegreenberg and I were surprised to see that there was no callback for NumberPicker on input, like there is for slider (`drag`). We decided that it made some sense to use the `onChange` callback (to be renamed from `change` in this issue) passed to AccessibleValueHandler as the same pattern we do for Slider to AccessibleSlider.

This will also clean up the sound code.

**Comment by zepumph** [comment]
@jbphet do you mind reviewing this change, especially the logic in NumberPicker.

**Comment by jbphet** [comment]
Review complete.  For the most part this looks good, and I agree that it cleans up the sound code.

I made what I felt was an improvement to the logic for playing sounds, since it was derived from code I had originally created and struck me as a bit convoluted upon review.  Please have a look at that and make sure you're good with what I've done.

Also, the documentation for the `onChange` listener says:

> Callback when input occurs on the NumberPicker. This can be from mouse/touch or keyboard/PDOM.

I feel like this description doesn't match the name very well (why not call it inputListener if it's fired on input?), so I'd suggest changing it to something like, "Listener that is called when the value changes due to user interaction with this number picker..." or something like that.  We want to convey that it is fired on changes, but only when the changes occur due to interaction with the number picker as opposed to, say, a reset.

**Comment by zepumph** [comment]
>(why not call it inputListener if it's fired on input?)

That makes sense, to me. `change` and `input` are two DOMEvents, and so I could see it both ways. My slight preference is to keep it as is because it aligns with the name of the callback in AccessibleValueHandler. I think that all option names should be changed if any are. After hearing this, please create a new issue if you would like to further discuss the rename. 

I really liked your doc, and couldn't think of anything better. Thanks!

**Comment by jbphet** [comment]
Sorry, I think I was a little unclear.  When I said, "[W]hy not call it inputListener if it's fired on input?" I was trying to illustrate the possible confusion of a future developer, not making a suggestion.  I prefer the term `change` in this context too, so we are in agreement.

It seems that we're done here - closing.
