### ISSUE TITLE
Create a PlayStopButton

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#666]
For the Quick Access Menu we will need a PlayStopButton similar to PlayPauseButton. It will look like this
![image](https://user-images.githubusercontent.com/6396244/107282416-ee0d0980-6a28-11eb-9884-a418a96db26f.png)

It will share a lot with PlayPauseButton since the only difference is the icon. I am thinking about creating a supertype
PlayControlButton with a constructor that takes the isPlayingProperty, icon Node for the not-playing state, and options, to be extended by PlayPauseButton and PlayStopButton. @samreid you are listed as the author of PlayPauseButton, are you OK if I do this or would you rather do it a different way?

**Comment by samreid** [comment]
That sounds like a reasonable plan, thanks!

**Comment by jessegreenberg** [comment]
OK, cool thanks! I did this in the above commit. Would you mind reviewing?

**Comment by samreid** [comment]
I tested the new buttons in the scenery-phet harness, and reviewed the code.  Things are working nicely! I have a few questions. I know some of my review comments pertain to code that was around before the change for this issue, but this seemed like an appropriate time to bring them up.  If there is no time to work on them now, they can move to side issues to be separately prioritized and assigned.

- [ ] For git history, it would make more sense for PlayPauseButton to be renamed to PlayControlButton, then a new thin subclass PlayPauseButton to be created--especially if many of the "factor more things into the base class" recommendations above are accomplished (see other review recommendations).  I listed this one first since it might simplify things to do this before other steps.

- [ ] `radius: 28` duplicated in all 3 classes, it should be factored out.

- [ ] In this code, it looks like this should say "is false".  Also, it's odd to call this "stop" since only half of the subtypes are related to being stopped.  Maybe "notPlayingIcon"?

 > @param {Node} stopIcon - icon for when isPlayingProperty value is true

- [ ] I recommend to put affiliations in the author annotations like so:

 * @author Sam Reid (PhET Interactive Simulations)
 * @author Jesse Greenberg (PhET Interactive Simulations)

- [ ] I know this code predates your changes, but why are the icons embedded in Circles instead of Rectangles?  I actually don't see why we need circles at all, can't the icons be aligned by an appropriate ToggleNode.alignChildren option?

- [ ] Is there a reason why the play/pause button changes size and the play/stop button does not?  Was this requested in the design?

- [ ] PlayStopButton looks like it needs code like this, it should probably be moved to the parent:

```js
      // PDOM - accessible name for the button
      this.innerContent = isPlaying ? sceneryPhetStrings.a11y.playPauseButton.pause
                                    : sceneryPhetStrings.a11y.playPauseButton.play;
```

- [ ] I recommend moving `options.includeGlobalHotKey`, `valueOffSoundPlayer` and `valueOnSoundPlayer` to the base type, even if they are currently planned to be unused by PlayStopButton. Ideally all PlayPauseButton would do differently is supply different options to the base type.  The issue description has a good vision: "It will share a lot with PlayPauseButton since the only difference is the icon."

- [ ] PlayPauseButton has Binder code, but PlayStopButton does not.

- [ ] Could the structuring of these if statements be improved?  It's unclear why it is nested like this.  Maybe just flatten it all into one `if` statement.

```js
        if ( phet.joist.sim.supportsInteractiveDescription ) {
          if ( this.buttonModel.enabledProperty.get() ) {
            if ( event.key.toLowerCase() === KeyboardUtils.KEY_K && globalKeyStateTracker.altKeyDown ) {

              // only allow hotkey if this Node is accessibleDisplayed, so it cannot be used if removed from PDOM
              if ( this.pdomDisplayed ) {
```

- [ ] It's unclear why this unlink is conditional.  Can't it always be unlinked?

```js
    isPlayingProperty.link( isPlayingListener );

    // @private
    this.disposePlayPauseButton = () => {
      if ( isPlayingProperty.hasListener( isPlayingListener ) ) {
        isPlayingProperty.unlink( isPlayingListener );
      }
```

- [ ] For this code, why not use `event.getModifierState(keyArg);`?  It seems asymmetrical and like things may get out of sync if we have two sources of truth for the keys.

```js
event.key.toLowerCase() === KeyboardUtils.KEY_K && globalKeyStateTracker.altKeyDown
```

**Comment by jessegreenberg** [comment]
Thanks for reviewing! Starting with the first since it involves git history, I tried to move contents of PlayControlButton into PlayPauseButton then rename PlayPauseButton to PlayControlButton, so that PlayControlButton has the history of PlayPauseButton, but after doing that locally I can no longer see any history under PlayControlButton with Webstorm. Ill try using `git mv` instead of webstorm rename.

**Comment by samreid** [comment]
Would it work to do the following steps?

(a) revert the https://github.com/phetsims/scenery-phet/commit/1a65cfca9aa8fcfdc9994d418f14b3be7e0d1b73
(b) rename PlayPauseButton to PlayControlButton
(c) reapply the salient parts of https://github.com/phetsims/scenery-phet/commit/1a65cfca9aa8fcfdc9994d418f14b3be7e0d1b73 (this part may be manual)

I typically do a revert commit using WebStorm like so:

![image](https://user-images.githubusercontent.com/679486/107979742-57869e00-6f7c-11eb-92fd-0368bae38e6f.png)

**Comment by jessegreenberg** [comment]
That worked well, thanks! Those steps were done in the above commits. Moving on to remaining code review items.

**Comment by jessegreenberg** [comment]
> radius: 28 duplicated in all 3 classes, it should be factored out.

Each subtype needs the value to create its icon, but I moved the value to SceneryPhetConstants in https://github.com/phetsims/scenery-phet/commit/8670f3fa6a19e59767ec07c0b966f039921e0fb7

**Comment by samreid** [comment]
> PhET convention is to increase the size of the "Play" button when interaction with the sim does NOT unpause the sim.

What context will the Play Stop button be used in?  Will interacting with a stopped sim un-stop the sim?  Shouldn't this be accomplished by setting the `scaleFactorWhenPaused` to default to `1` (which it already does?). Then if we have a case where PlayStopButton needs to change size, it can just change the option?

Also, updating assignee since there are still some unchecked boxes a few comments up.

**Comment by jessegreenberg** [comment]
Regarding https://github.com/phetsims/scenery-phet/issues/666#issuecomment-779438735, the first usages will play/stop speech, I would likely use a `scaleFactorWhenPaused` value of 1. I don't feel too strongly, and In retrospect I could see it being requested for a PlayStopButton in the future, I will move it to the supertype.

**Comment by jessegreenberg** [comment]
OK, the rest of the review comments have been addressed or are back for feedback in https://github.com/phetsims/scenery-phet/issues/666#issuecomment-779391125. @samreid reassigning back to you.

**Comment by samreid** [comment]
All the changes look great, nice work.  I reopened https://github.com/phetsims/sun/issues/121 to ask if we should guard against those listener removals.  I made one commit to use child options for the intermediate nodes, can you please review that?

Regarding the nested if statements, I compared with and without nesting:

with nesting:

```js
        // only enabled if the sim supports interactive descriptions
        if ( phet.joist.sim.supportsInteractiveDescription ) {
          if ( this.buttonModel.enabledProperty.get() ) {
            if ( event.key.toLowerCase() === KeyboardUtils.KEY_K && globalKeyStateTracker.altKeyDown ) {

              // only allow hotkey if this Node is accessibleDisplayed, so it cannot be used if removed from PDOM
              if ( this.pdomDisplayed ) {
                isPlayingProperty.set( !isPlayingProperty.get() );

                const soundPlayer = isPlayingProperty.get() ? options.valueOnSoundPlayer : options.valueOffSoundPlayer;
                if ( soundPlayer ) { soundPlayer.play(); }
              }
            }
          }
        }
```

without nesting:

```js
        // only enabled if the sim supports interactive descriptions
        if ( phet.joist.sim.supportsInteractiveDescription &&
             this.buttonModel.enabledProperty.get() &&
             event.key.toLowerCase() === KeyboardUtils.KEY_K && globalKeyStateTracker.altKeyDown &&

             // only allow hotkey if this Node is accessibleDisplayed, so it cannot be used if removed from PDOM
             this.pdomDisplayed
        ) {
          isPlayingProperty.set( !isPlayingProperty.get() );

          const soundPlayer = isPlayingProperty.get() ? options.valueOnSoundPlayer : options.valueOffSoundPlayer;
          if ( soundPlayer ) { soundPlayer.play(); }
        }
```

and the without nesting seemed simpler to me, so I committed it.  Can you please review that commit as well?  Feel free to adjust or revert if it's not preferable to you.

After reviewing those 2 commits, this issue can be closed.

**Comment by jessegreenberg** [comment]
OK thanks! https://github.com/phetsims/scenery-phet/issues/666#issuecomment-780291309 looks good, closing.
