### ISSUE TITLE
StopwatchNode elapsed time not saved when previewing sim in Studio 

### ISSUE THREAD

**Issue by arouinfar** [phetsims/scenery-phet#676]
Noticed in https://github.com/phetsims/capacitor-lab-basics/issues/249, but appears to be a general problem with StopwatchNode.

Steps to reproduce:
1. Open a sim containing a StopwatchNode in Studio (such as capacitor-lab-basics, gas-properties, wave-on-a-string)
2. Start the stopwatch
   <img width="500" alt="Screen Shot 2021-04-29 at 4 20 22 PM" src="https://user-images.githubusercontent.com/8419308/116625521-03e2ea00-a907-11eb-9d08-c0927798a35b.png">
3. Preview Sim
4. The stopwatch in the previewed sim will be in the correct position, but it will not be running
   <img width="500" alt="Screen Shot 2021-04-29 at 4 20 28 PM" src="https://user-images.githubusercontent.com/8419308/116625573-1b21d780-a907-11eb-8862-2007b6f75715.png">

Oddly enough, I don't notice any issues when playing with the StopwatchNode in the state wrapper. The state of the StopwatchNode in the downstream sim always matches the upstream sim, even when pausing/stepping with the TimeControlNode.

**Comment by zepumph** [comment]
You can reproduce this easily in the state wrapper.

1. State wrapper
2. "Set State Rate" to 0 so it doesn't automatically set
3. in upstream, open stopwatch and start it
4. press "Set State Now" and notice that the stopwatch is blank
5. Now that the stopwatch is showing, you can press the "Set StateNow" button and the timeProperty does update in the downstream sim.


I don't have any solutions for this one, but perhaps it has something to do with how the listener order occurs. Note that it does not seem to be a mismatch between the NumberDisplay and the timeProperty, because I was able to get state in the buggy case (loaded studio sim) and it said the timeProperty value was 0.

**Comment by samreid** [comment]
I pushed a proposed fix and it appears to be working correctly in CLB studio.  @zepumph can you please review?

**Comment by zepumph** [comment]
Nice! Thanks for taking a look.

**Comment by samreid** [comment]
Self-assigning to double check in this sim and another context.  If it checks out, we can run it past @arouinfar.

**Comment by samreid** [comment]
It seems fine in Wave on a String.  @arouinfar can you please review?  Close if all is well.

**Comment by arouinfar** [comment]
Looks good in wave-on-a-string and capacitor-lab-basics, thanks!
