### ISSUE TITLE
Add Voicing to NumberPicker

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#725]
Since this extends AccessibleValueHandler (and therefore voicing), it isn't clear how related this will be to https://github.com/phetsims/sun/issues/730. 

It will support https://github.com/phetsims/ratio-and-proportion/issues/441 though.

**Comment by zepumph** [comment]
Implemented above. @jessegreenberg this was pretty straightforward, would you mind reviewing and seeing if GFLB still looks good to you.

**Comment by terracoda** [comment]
@zepumph, I just noticed that Mass Control number pickers on master are no longer getting context responses when context responses are checked in preferences. In the published version, GFLB's Number Pickers do get context responses, so maybe some changes here need a second look?

**Comment by zepumph** [comment]
@terracoda, I made https://github.com/phetsims/gravity-force-lab-basics/issues/320 to fix the issues I made in GFLB. Anything else to change in common code for NumberPicker?

**Comment by terracoda** [comment]
Oops, missed this issue. I'll review the work very soon.

**Comment by terracoda** [comment]
The Mass number pickers in GFLB and the Left and Right Value number pickers in RaP are working well, and seem to be working in the exact same way as well.

The reading blocks are different, but that is intentional. The Mass Control reading blocks in GFLB are not keyboard accessible (this is intentional) whereas the Current Challenge reading block is keyboard accessible (this is intentional).

**Comment by terracoda** [comment]
Assuming I can close this issue as Voicing for NumberPicker seems very nice.
