### ISSUE TITLE
Leverage existing beakers for code and design

### ISSUE THREAD

**Issue by marlitas** [phetsims/scenery-phet#740]
We observed in the design document that beakers look like this:
<img width="251" alt="Screen Shot 2022-04-15 at 10 53 02 AM" src="https://user-images.githubusercontent.com/42476338/163598730-3f5d87be-5db4-4184-82fc-204cdeac07c0.png">
In the illustrator document beakers look like this:
<img width="176" alt="Screen Shot 2022-04-15 at 10 56 21 AM" src="https://user-images.githubusercontent.com/42476338/163598779-325b6085-1c3f-446f-a001-fceef600d3f0.png">
In fractions intro beakers look like this:
<img width="195" alt="Screen Shot 2022-04-15 at 10 57 06 AM" src="https://user-images.githubusercontent.com/42476338/163598842-6ce378cf-4d71-4911-a383-281f6020104a.png">
Energy Forms and Changes has a beaker that looks like this:
<img width="593" alt="Screen Shot 2022-04-15 at 10 51 22 AM" src="https://user-images.githubusercontent.com/42476338/163598712-64592693-5f7f-4543-87ac-63ce0f5ab2d3.png">
We also saw that Molarity has a somewhat similar beaker that looks like this:
<img width="595" alt="Screen Shot 2022-04-15 at 10 58 57 AM" src="https://user-images.githubusercontent.com/42476338/163598993-db418f34-8a42-43a4-8adc-9447ffec903b.png">

- We saw no common code at the moment. Checked scenery Phet for common code implementations of beakers and could not find any. 
- Are there any other sims that use a beaker in this same fashion?
- Should we generalize the code in fraction intro, so that it can support both sims?
- If we believe the look and feel of the proposed cups for Mean Share and Balance is superior, do we also want to apply that to the fraction sim?

Advantages of reusing code:
- consistency across sims
- reducing code footprint (not duplicating)
- Retrofitting to Phet-io may be easier?

In all we observed 5 Beaker Nodes across all sims. Some are 2D and some are 3D.

**Comment by samreid** [comment]
@marlitas and I will use the new process described in https://github.com/phetsims/perennial/issues/269 to transfer the history from fractions-common to scenery-phet.  We reviewed several implementations and agreed that seems like a good starting point.

**Comment by marlitas** [comment]
BeakerNode has been implemented into Mean: Share and Balance, as well as Fractions Common. Manually and fuzz tested on Fractions Intro and Fractions: Mixed Numbers. I would appreciate a review from a more experienced dev to make sure a). I didn't break anything, and b). gather feedback on code written.

**Comment by chrisklus** [comment]
From 6/16/22 dev meeting:

@pixelzoom volunteered to review, thanks!

**Comment by pixelzoom** [comment]
When we add a new UI component to common code, we typically add a demo of that component to the scenery-phet (or sun) demo application.  In the above commit, I've added a demo for BeakerNode to the "Components" screen of scenery-phet. @marlitas let me know if you have any questions about this.

**Comment by pixelzoom** [comment]
This bit is a problem:

```typescript
export type BeakerNodeOptions = SelfOptions & StrictOmit<NodeOptions, 'children'>;
...
    const mergedOptions = optionize<BeakerNodeOptions, SelfOptions, NodeOptions>()( options, { children: children } );
     super.mutate( mergedOptions );
```

The client is allowed to pass in `providedOptions.children`, and then the `optionize` call blows it away.  Since BeakerNode has control over the `children` option, this is a place where narrowing should be applied to the definition of `BeakerNodeOptions`.

From [Options (TypeScript)](https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md#options-typescript):
> (2) Use [StrictOmit](https://github.com/phetsims/phet-core/blob/master/js/types/StrictOmit.ts), [PickRequired](https://github.com/phetsims/phet-core/blob/master/js/types/PickRequired.ts), and [PickOptional](https://github.com/phetsims/phet-core/blob/master/js/types/PickOptional.ts) to narrow the API provided by your options type.

The above commit addresses this via this type definition:

```typescript
export type BeakerNodeOptions = SelfOptions & StrictOmit<NodeOptions, 'children'>;
```

It also replaces `super(); ... super.mutate(...);` with one call to `super( options )`.    I generally try to avoid `mutate` unless it's really necessary, because it's a bit less efficient. 

@marlitas let me know if you have any questions about this.

**Comment by pixelzoom** [comment]
In the above commits, a few things about the "ticks visible" API...

* While the UI may be labeled with things like "Show ticks", we typically use `blahVisible` and `setBlahVisible` in APIs, now "show".  So the option is now `ticksVisible`, and the method is `setTicksVisible( visible: boolean ): void`.
* Visibilty of ticks was being controlled using `addChild` and `removeChild`.  These are relatively expensive operations. So it's preferred to change visibility of Nodes, rather than change the scenegraph structure. The exception to this is if you're concerned about the bounds changing.  In this case, the tick marks are on the _inside_ of the beaker, so their visibility has no affect on bounds.

@marlitas let me know if you have any questions about this.

**Comment by pixelzoom** [comment]
BeakerNode links to a Property that it does not own (`solutionLevelProperty`) but did not implement `dispose`.  That's a memory leak, and has been corrected in the above commit.  

@marlitas let me know if you have any questions about this.

**Comment by pixelzoom** [comment]
`numTicks` is used throughout BeakerNode, and violates this convention from [Coding Conventions](https://github.com/phetsims/phet-info/blob/master/doc/phet-software-design-patterns.md#options-typescript):

>  Names (types, variables, properties, Properties, functions,...) should be sufficiently descriptive and specific, and should avoid non-standard abbreviations. For example:

```js
const numPart = 100;            // incorrect
const numberOfParticles = 100;  // correct

const width = 150;              // incorrect
const beakerWidth = 150;        // correct
```

So `numTicks` has been changed to `numberOfTicks` in the above commit.

**Comment by pixelzoom** [comment]
There were many color options that were defined to be of type `ProfileColorProperty` or `ProfileColorProperty | Color`.  This is unnecessarily restrictive.  Scenery typically supports colors that are of type `IColor` or `IPaint`.  `IColor` is likely sufficient here (no need to provide gradients, for example) so I've changed to `IColor` in the above commit.

There is still one such option that needs to be addressed:

```typescript
  solutionFill?: ProfileColorProperty;
...
    const solutionGlareFill = providedOptions?.solutionFill?.value.colorUtilsBrighter( 0.5 );
    const solutionShadowFill = providedOptions?.solutionFill?.value.colorUtilsDarker( 0.2 );
```

It would be preferrable to have `solutionFill?: IColor`, then compute `solutionGlareFill` and `solutionShadowFill` correctly based on the actual type of `solutionFill`.

**Comment by pixelzoom** [comment]
- [ ] Looking at SceneryPhetColors.ts, the name of this color is much too vague:

```
  stroke: new ProfileColorProperty( sceneryPhet, 'stroke', { default: 'black' } )
```

It's used as the default for 2 things in BeakerNode.ts:

```
      stroke: SceneryPhetColors.stroke,
...
      tickStroke: SceneryPhetColors.stroke
```

So:
* Choose a better name for this field.
* Consider decoupling BeakerNodeOptions.stroke and BeakerNodeOptions.tickStroke by having 2 separate default colors in SceneryPhetColors.ts.

**Comment by pixelzoom** [comment]
- [ ] Are`xRadius/yRadius` and `beakerWidth/beakerHeight` 2 different ways of specifying the same thing?

It's difficult to tell for sure because they are not documented.  But if they are the same, recommended to get rid of one of those ways.  It's generally not a good idea to have 2 ways of doing the same thing, especially without checks to guarantee that they are mutually exclusive.

And this line (for example) is troubling:

```typescript
    options.xRadius = providedOptions?.beakerWidth ? providedOptions.beakerWidth / 2 : options.xRadius;
```

If the caller specified `beakerWidth`, it blows away not only the `xRadius` default, but also any `xRadius` value that the caller specified.

**Comment by pixelzoom** [comment]
- [ ] `solutionLevelProperty` is assumed to have range [0,1] at most.

... and there's nothing that verifies that assumption.  And things get really weird if that `solutionLevelProperty` has a different range. For example, here's scenery-phet demo with `solutionLevelProperty` range [0,5]:

<img width="337" alt="screenshot_1700" src="https://user-images.githubusercontent.com/3046552/174168653-a8e71458-8e57-4541-a290-366640e084f7.png">

Recommended to change the constructor param and add an assertion, like this:

```diff
-  public constructor( solutionLevelProperty: NumberProperty, providedOptions?: BeakerNodeOptions ) {
+  public constructor( solutionLevelProperty: RangedProperty, providedOptions?: BeakerNodeOptions ) {
+    assert && assert( solutionLevelProperty.range.min >= 0 && solutionLevelProperty.range.max <= 1 );
```

Then usages will need to call `asRanged()`, like this in WaterCup3DNode.ts:

```diff
- const waterCup = new BeakerNode( cup3DModel.waterLevelProperty, {
+ const waterCup = new BeakerNode( cup3DModel.waterLevelProperty.asRanged(), {
```

**Comment by pixelzoom** [comment]
- [ ] Change the `@author`, currently:

```
@author Jonathan Olson <jonathan.olson@colorado.edu>
````

**Comment by pixelzoom** [comment]
Code review is done.  Remaining issues are identified by checklist items in the above comments. 

Back to @marlitas. Let me know if you have questions.

**Comment by pixelzoom** [comment]
Related to the changes to `xRadius/yRadius` and `beakerWidth/beakerHeight` that @marlitas and I paired on in https://github.com/phetsims/scenery-phet/commit/75f32c1c37304f24540c5d5a23167957bd1211e1 ...

I realized that we hadn't addressed the constants `DEFAULT_X_RADIUS` and `DEFAULT_Y_RADIUS`.   That's been done in the above commits. Summary:
* `DEFAULT_X_RADIUS` was deleted because BeakerNodeOptions.xRadius no longer exists
* `DEFAULT_Y_RADIUS` was replaced by `this.yRadiusOfEnds`.  Callers (e.g. WaterCup3DNode should be using the _actual_ value in their calculations, not the default value.

**Comment by pixelzoom** [comment]
Reopening.  

I didn't notice in my original review (probably because I was distracted by the `@author` annotation), but this file has an inadequate header description.  From [Coding Conventions](https://github.com/phetsims/phet-info/blob/master/doc/coding-conventions.md):

> - [ ] Documentation at the top of .js files should provide an overview of purpose, responsibilies, and (where useful) examples of API use. If the file contains a subclass definition, it should indicate what functionality it adds to the superclass.

The current header comment:

```
/**
 * Displays a beaker graphic
 *
 * @author Marla Schulz <marla.schulz@colorado.edu>
 */
```

... does not meet this convention.  This class does more than just display a beaker graphic. There's solution in the beaker, optional tick marks, ...

I took a stab at an improved description in the above commit. @marlitas please review. Feel free to modify and close.

**Comment by marlitas** [comment]
Class documentation addressed. Closing!
