### ISSUE TITLE
Touch outline doesn't reflect touch area with locales other than English

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/scenery-phet#766]
When testing Gravity and Orbits (https://github.com/phetsims/qa/issues/830), using ?showPointerAreas, when I change locale, the outline for touch isn't accurate, but where touch works/doesn't work is. 
For example, when the locale is español, the touch outline doesn't extend to the end of the text. However, if I touch outside the red outline on the iPad, the checkbox will get checked/unchecked. 

https://user-images.githubusercontent.com/87318828/187283583-dc82db46-972d-4220-9ab7-38a0cf272a73.mov

This also looks different than the published version. 
<img width="263" alt="Screen Shot 2022-08-29 at 3 07 49 PM" src="https://user-images.githubusercontent.com/87318828/187283872-0cbab1fd-6d91-469c-b614-ed9b1dcb076a.png">

FYI @samreid since this was spotted in Gravity and Orbits.

**Comment by zepumph** [comment]
We found that CheckboxPanel in GAO code was overwriting the touchArea for checkbox, but not the mouse area, so the common Checkbox mouseArea was dynamically updating, but the touchArea was smart enough to not overwrite client code. Deleting these lines "solves" the dynamic part of the problem but we need to be able to support this custom touch area.

https://github.com/phetsims/gravity-and-orbits/blob/a53c5d1f91cc03564db6c531a60567880836f1a6/js/common/view/CheckboxPanel.ts#L137-L145

@samreid will investigate further. He would like to try to use VerticalCheckboxGroup in GAO.

A question we still have: Why does it still work to touch outside the touch area on the Node?

**Comment by samreid** [comment]
I converted Gravity and Orbits to use VerticalCheckBoxGroup, and that went well.  Next, I saw that the touch/mouse area bounds weren't updating on locale switch due to these guards: `_isTouchAreaCustomized` and `_isMouseAreaCustomized` which were enabled by VerticalCheckboxGroup manually setting the Checkbox pointer area and touch area.  By sending those options through the constructor, it can remain dynamic.

@zepumph can you please review that commit: https://github.com/phetsims/sun/commit/b12fc7b035a6a7cb0a9cdd03611a2af0c94c6eff and test?

**Comment by zepumph** [comment]
Yes. That looks amazing. Thanks!

**Comment by samreid** [comment]
Excellent, thanks!  Closing.

**Comment by samreid** [comment]
Actually @Nancy-Salpepi can you please spot test in master?

**Comment by Nancy-Salpepi** [comment]
Looks good on master with mac and the iPad. @samreid thanks for showing how to test all locales on master at status!

**Comment by Nancy-Salpepi** [comment]
I am seeing this issue with the options panel in https://github.com/phetsims/qa/issues/844 and https://github.com/phetsims/qa/issues/845. The touch area outline doesn't accurately show touch area. 

For example--if I touch outside the touch area for the Show Bond Angles checkbox, but inside the blue mouse area, it works. 
<img width="335" alt="Screen Shot 2022-10-25 at 11 39 24 AM" src="https://user-images.githubusercontent.com/87318828/197820387-4143cb54-3287-4069-9252-a347476ddc85.png">

**Comment by arouinfar** [comment]
Thanks @Nancy-Salpepi. @jonathanolson I do not think this is a blocking issue. Looks like the touch behavior is correct, but isn't being displayed correctly with `showPointerAreas`. Since `showPointerAreas` is an internal tool, this has no impact on user experience.

**Comment by zepumph** [comment]
In https://github.com/phetsims/ratio-and-proportion/issues/540 we once again had to convert a usage of `checkbox.setTouchArea` to use the option in order to support dynamic locale. That doesn't seem ideal, but perhaps it is necessary for the Checkbox API.

**Comment by Nancy-Salpepi** [comment]
Noting that this issue is also present in https://github.com/phetsims/qa/issues/866.

**Comment by pixelzoom** [comment]
12/22/2022 phet-io meeting:

Not blocking for ph-scale 1.6.

**Comment by jonathanolson** [comment]
I solved this for molecule-shapes in https://github.com/phetsims/molecule-shapes/issues/239. It looks like it was actually broken, and looks like it will be sim-specific (whether the sim is trying to add custom touch areas in ways that don't respect dynamic updates).

**Comment by pixelzoom** [comment]
It's nice that @jonathanolson was able to resolve this one specific case for molecules-shapes. It would be nice if he identified where and how he addressed it, so we can see if there's something similar to be done in other sims. I found commit https://github.com/phetsims/molecule-shapes/commit/f393695d2ff5ab3d0eaf96964ea7beb9ed4af837, but there are a lot of changes there that don't have to do with touchArea, so difficult to see what's relevant.

I suspect there is a more systemic problem, and that we've generally failed to address dynamic locale for pointer areas.  Potential general problems:

(1) In 12/22/2022 @samreid tested that UI components still work after a dynamic string changes. But he did not verify that the pointer areas are still dilated/erroded as desired.  I doubt that they are.

(2) Where mouseArea and touchArea are being explicitly set, they will presumably need to be set in a boundsProperty listener, not just one time.  I don't see how scenery could know how much dilation/erosion was initially applied, and then automatically adjust when bounds change. (And pointer areas are not necessarily even rectangles, they can be any Shape.)

(3) Many common-code components have options for dilation.  Looking at RectangularButton for example, it has the options shown below. It only applies those options once (on instantiation) and does not re-apply them if its boundsProperty changes.

```typescript
  // pointer area dilation
  touchAreaXDilation?: number;
  touchAreaYDilation?: number;
  mouseAreaXDilation?: number;
  mouseAreaYDilation?: number;

  // pointer area shift, see https://github.com/phetsims/sun/issues/500
  touchAreaXShift?: number;
  touchAreaYShift?: number;
  mouseAreaXShift?: number;
  mouseAreaYShift?: number;
```

(4) For those components in (3), what happens if the pointer area options are not used, and mouseArea/touchArea are set explictly after instantiation? This creates a listen ordering problem.   For example, which will run first -- RectangularButton's boundProperty listener that update according to the options shown in (2)? Or boundsPropery listener that was added after instantiation below?

```typescript
const button = new RectangularButton( { 
   content: new Text( someStringProperty, ... ),
   ...
 } );
button.boundsProperty.link( () => {
  button.touchArea = button.localBounds.dilateXY( 5, 5 );
} );
``

So... Self-assigning to investigate.  Assigning back to @jonathanolson to take a more thorough/general look. And adding to the Developer Meeting board.

**Comment by pixelzoom** [comment]
No response from @jonathanolson.

@samreid and I looked at this a bit. He worked on https://github.com/phetsims/molecule-shapes/commit/f393695d2ff5ab3d0eaf96964ea7beb9ed4af837, so helped me identify the relevant part of that commit.  The relevant part was OptionsNode.js.  It was converted for a VBox to a VerticalCheckboxGroup, which handles resizing of pointer areas.  (Describing that change in the first place would've saved 2 developers from having to work on it. Just sayin'...)

RectangularButton does look like it might be managing its pointer areas in the Multilink on line 180.  So we suspect that it's doing the right thing.  Hopefully other UI components that have similar options are also updating this pointer areas.

Re (4) in https://github.com/phetsims/scenery-phet/issues/766#issuecomment-1364541703 ... We don't have a good solution for this. If a UI component has options for pointer areas, and is managing its pointer areas, then you shouldn't be setting pointer areas separately.   So I guess this is in the "don't do that" category.   And if you do that, you're likely to get burned.

Back to @arouinfar. @jonathanolson assigned you in https://github.com/phetsims/scenery-phet/issues/766#issuecomment-1364177402 and has something he wants you to review.

**Comment by arouinfar** [comment]
> Back to @arouinfar. @jonathanolson assigned you in https://github.com/phetsims/scenery-phet/issues/766#issuecomment-1364177402 and has something he wants you to review.

Thanks @pixelzoom. I reviewed and closed in https://github.com/phetsims/molecule-shapes/issues/239

This is tagged for developer meeting, so I assume there is more to discuss. Since there were some open questions for @jonathanolson I'll kick it back to him.

**Comment by pixelzoom** [comment]
Removed from Developer Meeting board.  I don't think there's anyting left to discuss here. Feel free to reopen if you disagree.
