### ISSUE TITLE
Problems with SliderControlsKeyboardHelpSection

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#784]
Related to https://github.com/phetsims/scenery-phet/issues/780.  This was buggy to begin with, but may manifest in more tragic ways now that we've converted to using StringProperty.  

There are multiple issues with SliderControlsKeyboardHelpSection.ts:

- [ ] ~~All `PatternStringProperty` should be converted to `DerivedProperty`, because there are multiple StringProperty dependencies, not just a pattern StringProperty.~~

- [ ] ~~`keysStringProperty` and `shiftKeysStringProperty` are both Properties. They are currently used as values when filling in patterns, when they should be dependencies of DerivedProperty.~~

- [x] `options.verbString`, `options.sliderString`, `options.verbString`, `options.minimumString`, and `options.maximumString` are all `{string | TReadOnlyProperty<string>}`.  They are currently used as values when filling in patterns, ~~when they should be dependencies of DerivedProperty.~~  And it would simplify things if they were of type `TReadOnlyProperty<string>`, and renamed accordingly to have a "Property" suffix.

**Comment by zepumph** [comment]
> * All `PatternStringProperty` should be converted to `DerivedProperty`, because there are multiple StringProperty dependencies, not just a pattern StringProperty.

I'm not sure I understand, could you paste a proposal example/patch in here. These seem like reasonable usages of PatternStringProperty to me.



> * `keysStringProperty` and `shiftKeysStringProperty` are both Properties. They are currently used as values when filling in patterns, when they should be dependencies of DerivedProperty.

PatternStringProperty supports values as Properties now, and listens for when the `values` object Properties change. 

> * `options.verbString`, `options.sliderString`, `options.verbString`, `options.minimumString`, and `options.maximumString` are all `{string | TReadOnlyProperty<string>}`.  They are currently used as values when filling in patterns, when they should be dependencies of DerivedProperty.  And it would simplify things if they were of type `TReadOnlyProperty<string>`, and renamed accordingly to have a "Property" suffix.

I agree, let's rename those options and tighten the types into just the string Property. More generally though, perhaps we should discuss, maybe with @jonathanolson, because it appears that we have very different understandings of how PatternStringProperty should be used. My understanding (and what I have experienced refactoring the code) is that it can completed replace all usages of DerivedProperty which was an intermediate pattern used to get rid of StringUtils.fillIn. @jonathanolson wrote it very flexibly such that it is quite tolerant of values being Properties or strings. Thank you for that!

Let me know if you want to talk.

**Comment by pixelzoom** [comment]
> I'm not sure I understand, could you paste a proposal example/patch in here. These seem like reasonable usages of PatternStringProperty to me.

Sorry, I didn't realize that PatternStringProperty harvests dependences from its 2nd argument.

> PatternStringProperty supports values as Properties now, and listens for when the values object Properties change.

I didn't realize that. 

> More generally though, perhaps we should discuss, maybe with @jonathanolson, because it appears that we have very different understandings of how PatternStringProperty should be used. ...

Not necessary. I wasn't aware of how it harvested dependencies from its 2nd argument. So I'll be using PatternStringProperty more in the future.  I may or may not eagerly replace DerivedProperty with PatternStringProperty.

> I agree, let's rename those options and tighten the types into just the string Property. 

@zepumph will you handle the renaming?

**Comment by zepumph** [comment]
Excellent. This work has been done: 

https://github.com/phetsims/scenery-phet/blob/6c410d28151f4ffb69c699e86da18ac64aafdae6/js/keyboard/help/SliderControlsKeyboardHelpSection.ts#L59-L67

Closing
