### ISSUE TITLE
Blank keyboard help keys in translations?

### ISSUE THREAD

**Issue by zepumph** [phetsims/scenery-phet#786]
From https://github.com/phetsims/ratio-and-proportion/issues/499#issuecomment-1297705112, I see that hebrew and a few other languages have made some keys blank in the keyboard help dialog, you can reproduce this with 

http://localhost:8080/ratio-and-proportion/ratio-and-proportion_en.html?brand=phet&ea&debugger&voicingInitiallyEnabled&printVoicingResponses&preferencesStorage&locales=*&keyboardLocaleSwitcher&locale=iw

When I go to babel, it looks a bit like there is some back and forth about how to translate the keys. Search for `newValue": ""` https://github.com/phetsims/babel/blob/da0708671f8e46c53d995c28d8edd57e26f3235b/scenery-phet/scenery-phet-strings_iw.json

<img width="598" alt="blankbuttons" src="https://user-images.githubusercontent.com/41024075/199112673-4fe9b55e-2a3a-4891-b470-d27d79d06f98.png">

@jbphet, what should we do here? If anything? I think this relates to an issue you just had a design meeting about.

**Comment by jbphet** [comment]
This appears to be caused by the problem discussed in https://github.com/phetsims/chipper/issues/1343.  In summary, it's because our string-handling code is not falling back to the English values when it encounters a zero-length string.  That issue is assigned to @jonathanolson at the moment.  If resolving this is urgent, I'd suggest raising the priority of that issue.

**Comment by zepumph** [comment]
Yes indeed! Here it is falling back to english for blank translations:

![image](https://user-images.githubusercontent.com/6856943/200627971-c521d81f-7c47-4a9e-928a-a5eeb941efaf.png)


Closing. Please reopen if for some reason that commit doesn't make it to production.
