### ISSUE TITLE
Replace alt icon with an Option icon in macOS

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#793]
Alt is more specific to Windows, it would be nice if it showed Option with running on macOS.

**Comment by samreid** [comment]
It seemed straightforward, so I committed changes. It looks like this on my mac:

<img width="1103" alt="image" src="https://user-images.githubusercontent.com/679486/211170004-bf890e45-ef84-4ed1-a174-7f17f2e94bd3.png">

This should be tested on windows and reviewed.

**Comment by jessegreenberg** [comment]
This looks great, thanks @samreid! The above commit works well. I tested on Windows and saw that it still says "Alt", and tested on Mac and saw "Option". I reviewed other help dialogs (geometric-optics, quadrilateral, BASE) and did not see any layout problems from the additional characters.

For completion I will update the screen reader descriptions describing combinations of alt as well, there are not very many of them.

**Comment by jessegreenberg** [comment]
OK, that seemed like a reasonable way to refactor and use the "Alt"/"Option" strings in descriptions. Verified by looking at the PDOM while the Keyboard Shortcuts dialog is open and listening with Voicing in quadrilateral.

@samreid would you like to review this accessibility change?

**Comment by samreid** [comment]
I reviewed the code changes and confirmed the PDOM is correct:

<img width="584" alt="image" src="https://user-images.githubusercontent.com/679486/211629437-c888c742-d0bf-419a-8507-b7c34a65b56f.png">

Everything seems working and reasonable.  My only concern is about the way variables are named in an alt-centric way.  For instance `"value": "Reset All with {{altKey}} plus R."` seems to say it is an alt key, but some other platforms just have a different name for alt.  I'm fine if we agreed on that convention as a team, but in the absence of further information it seems it would be more symmetrical to balance the names.

@jbphet said, perhaps we would call it a modifier key.  Since it is a different modifier key on different platforms.  So maybe it would be called `modifierKey`?

@jessegreenberg what do you think?

**Comment by jessegreenberg** [comment]
Oh OK - I went with `altOrOption` just to move forward but can revert/rename. 

According to https://en.wikipedia.org/wiki/Alt_key:
>The Alt key Alt [...] on a computer keyboard is used to change (alternate) the function of other pressed keys. Macintosh keyboards equate the Alt key with the [⌥ Option] key [...].

And at techpedia.com I found
> An alternate key (Alt key) is a key that is present on most computer keyboards and is considered a modifier key that can used similarly to the shift or control keys

So how about `alternate`? Or I am fine leaving as `alt` and reverting my above commits.

**Comment by samreid** [comment]
I don't feel strongly about this naming, and `altOrOption` seems OK to me.

**Comment by jessegreenberg** [comment]
OK, thanks. Thanks for taking on this issue and reviewing, Ill go ahead and close.
