### ISSUE TITLE
Memory leak in BasicActionsKeyboardHelpSection

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#805]
If this block is executed, `zeroToNineIcon` is never disposed.  Note that `options.withKeypadContent` is currently true only for my-solar-system.

```ts
    if ( options.withKeypadContent ) {

      // 'Set values within keypad'
      const zeroToNineIcon = KeyboardHelpIconFactory.iconToIcon( new NumberKeyNode( 0 ), new NumberKeyNode( 9 ) );
      const setValuesInKeypadRow = KeyboardHelpSectionRow.labelWithIcon(
        SceneryPhetStrings.keyboardHelpDialog.setValuesInKeypadStringProperty, zeroToNineIcon, {
          labelInnerContent: SceneryPhetStrings.a11y.keyboardHelpDialog.general.setValuesInKeypadDescriptionStringProperty
        } );
      content.push( setValuesInKeypadRow );
    }
```

**Comment by pixelzoom** [comment]
@zepumph would you please review? Close if OK.

**Comment by zepumph** [comment]
That looks complete to fix the leak. Thank for that.

Yesterday we spoke about the tradeoff to disposing everything vs disposing only when needs disposing. `NumberKeyNode` here does not need disposal, since it just creates a local Text based on the provided value, but it partially goes against something I heard you say yesterday about just disposing everything just to be safe. What do you prefer in this situation, as we are still teasing out the pattern.

**Comment by pixelzoom** [comment]
I'm OK with not disposing `NumberKeyNode` - it seems low risk.
