### ISSUE TITLE
Accesibility support for Stopwatch Node

### ISSUE THREAD

**Issue by AgustinVallejo** [phetsims/scenery-phet#820]
First encountered in https://github.com/phetsims/keplers-laws/issues/174, when using keyboard input to focus the Stopwatch Node, it only focuses the buttons, but doesn't allow for keyboard dragging and displacing. 

The restart and play/pause buttons also do not have accessible name, and are displayed as blanks in the A11y view.

**Comment by jessegreenberg** [comment]
One of the reasons we thought this should be a common code issue is because StopwatchNode has built in support for drag/drop behavior through DragListener. So it would make sense to have alt input support as well.

A couple of design questions I have:
- Should alt input for StopwatchNode use GrabDragInteraction (spacebar/enter to pick up) or just a KeyboardDragListener (focus and move right away)? Or does it need to optionally support either?
- In https://github.com/phetsims/keplers-laws/issues/174, we noticed that the stopwatch can be dragged by the buttons because of event bubbling. Is that acceptable or should we find a way to prevent that?

**Comment by jessegreenberg** [comment]
@arouinfar @DianaTavares @AgustinVallejo and I had a meeting where we discussed these things.

- For Kepler's Laws, we prefer KeybaordListener to GrabDragInteraction because other components (and common components like the measuring tape) use KeyboardListener. We will add  KeyboardListener to the StopwatchNode for now and defer adding GrabDragInteraction until it is needed. I also wonder if the complexity of GrabDragInteraction warrants a subclass of StopwatchNode.
- It is OK that the StopwatchNode can be dragged from its child buttons. We will add a group focus highlight around the StopwatchNode to indicate that the entire StopwatchNode can still be controlled by the user.

@AgustinVallejo and I will meet tomorrow to pair on this change.

**Comment by jessegreenberg** [comment]
@AgustinVallejo and I paired on adding a KeyboardDragListener to the StopwatchNode in the above commits. Closing.
