### ISSUE TITLE
Handle default sounds for DragListener and KeyboardDragListener in scenery

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/scenery-phet#849]
Over in https://github.com/phetsims/graphing-lines/issues/137#issuecomment-1861693224, @amanda-phet and I discovered that DragListener and KeyboardDragListener apparently have an (unofficial?) default design. tambo has sounds to be used for "grab" and "release" interactions.   

While it's a default sound design, it's not supported in common code. Sims must implement it, using some variation of this code:

```ts
import grab_mp3 from '../../../../tambo/sounds/grab_mp3.js';
import release_mp3 from '../../../../tambo/sounds/release_mp3.js';
...

// Create sound clips.
const dragClipOptions = {
  initialOutputLevel: ... // a value between 0 and 1
};
const grabClip = new SoundClip( grab_mp3, dragClipOptions );
const releaseClip = new SoundClip( release_mp3, dragClipOptions );

// Add the sound clips to the soundManager.
soundManager.addSoundGenerator( grabClip );
soundManager.addSoundGenerator( releaseClip );

// Wire the sounds up to DragListener interactions.
... new DragListener( {

   start: () => {
     grabClip.play();
     ...
   },
   ...
   end: () => {
     releaseClip.play();
     ...
   }
} );

// Wire the sounds up to KeyboardDragListener interactions.
... new KeyboardDragListener( {

   start: () => {
     grabClip.play();
     ...
   },
   ...
   end: () => {
     releaseClip.play();
     ...
   }
} );
```

There are also variations of the above code that use `press: () => grabClip.play()` and `release: () => releaseClip.play()`.

This duplication is very undesirable. It's unnecessary work.  It results in inconsistent implementation and inconsistent behavior (e.g output levels are all over the place). It's also easy to omit, if the developer and designer are not aware of this pattern (as I wasn't until a couple of hours ago.)

Let's investigate moving the default sound design (and the above code) into scenery, with options to specify an alternative sound design.

**Comment by zepumph** [comment]
@AgustinVallejo and I believe that we are done with the work for this issue. Next step is to have a reviewer look over the work.  We recommend @jbphet take the review with an eye for how the tambo-related code is implemented.

Focus for reviewer:
* Please look through the implementations of `RichDragListener` and `RichKeyboardDragListener`. How do you like the API, and do you think it is complete?
* Please look into the usages we have so far. Not all grab/release sounds were converted, but enough that we feel that the API supports needed cases moving forward.

Questions for reviewer (to think about while working on the above)
* What about the shared sound player called grabSoundPlayer() [Handle default sounds for DragListener and KeyboardDragListener in scenery #849](https://github.com/phetsims/scenery-phet/issues/849)
* The API doesn't support passing in a `SoundClip`. i.e. RatioHalf.ts. I'm not sure we should support this, but just wanted to note it.
* Sometimes the sound can be on focus/blur instead of start/end. Should we support that? I believe we may get to a point where ~50% of keyboard drag listeners want that behavior, depending on the sim-specific context. 
* Note that RichKeyboardDragListener and RichDragListener.js are identical except for the string 'Keyboard' (likely fixed by [Combine DragListener and KeyboardDragListener into a single class scenery#1614](https://github.com/phetsims/scenery/issues/1614)).

**Comment by pixelzoom** [comment]
These drag listeners are not behaving properly when they've been interrupted (eg by calling `interruptSubtreeInput`).  See https://github.com/phetsims/graphing-lines/issues/156.

If in the case of RichDragListener, I suspect that this patch will fix the problem.  But I do not have a multitouch device availabe, so I cannot test.

```diff
Subject: [PATCH] interruptSubtreeInput when resetAllButton is pressed, https://github.com/phetsims/graphing-lines/issues/156
---
Index: js/RichDragListener.ts
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/RichDragListener.ts b/js/RichDragListener.ts
--- a/js/RichDragListener.ts	(revision 69f356768c26e0d2af3ca23e272f118cc16f3ef2)
+++ b/js/RichDragListener.ts	(date 1713281208977)
@@ -87,7 +87,7 @@
       const previousEnd = options.end;
       options.end = ( ...args ) => {
         previousEnd && previousEnd( ...args );
-        releaseClip.play();
+        !this.interrupted && releaseClip.play();
       };
     }
 ```

In the case of RichKeyboardDragListener, I don't see how to address this.  KeyboardDragListener has no `interrrupted` flag.

Back to @zepumph and @AgustinVallejo with high priority.  Graphing Lines is in RC testing.

**Comment by jbphet** [comment]
Unassigning myself until the next review is needed.

**Comment by zepumph** [comment]
I believe first we should update the KeyboardDragListener API to support the `interrupted` flag. Then this will be a simple patch, as @pixelzoom mentioned. I'll touched base with @jessegreenberg about his current KeyboardDragListener work. I will just patch things in main, since Graphing Lines is already in RC (making for an easier cherry pick).

**Comment by zepumph** [comment]
Alright. @pixelzoom, can you please see if this fixed your problem for Graphing Lines. 

To Cherry pick:

https://github.com/phetsims/scenery-phet/commit/1af656ae5c66725be4f8480df346bf4c6960446c
https://github.com/phetsims/scenery/commit/5ee1b7c567172433daecaf1e90d4620601c3a4dd

**Comment by pixelzoom** [comment]
> Alright. @pixelzoom, can you please see if this fixed your problem for Graphing Lines.

I don't have a multitouch device available for testing.  So I've asked @Nancy-Salpepi to verify in https://github.com/phetsims/graphing-lines/issues/156#issuecomment-2064895893.

**Comment by pixelzoom** [comment]
Cherry picking has been completed for graphing-lines 1.4 and graphing-slope-intercept 1.2.

Back to @jbphet to complete the review requested in https://github.com/phetsims/scenery-phet/issues/849#issuecomment-2021595684.

**Comment by pixelzoom** [comment]
@jbphet ping. Let's get this reviewed and closed.

**Comment by jessegreenberg** [comment]
Note that `RichDragListener` has been renamed to `RichPointerDragListener`. This rename was discussed over slack and will allow `RichDragListener` to be a listener that combines `RichPointerDragListener` and `RichKeyboardDragListener`, supporting both forms of input with a single listener.

However, my rename lost git history so I am going to redo the scenery-phet commits.

**Comment by jbphet** [comment]
I'm sorry it's taken me so long to start reviewing this, but, well, higher priorities.

I've taken an initial look, and have some big questions before moving on to the next steps.

1. It looks like this has evolved a lot, and the classes that I should now review (since I believe I'm being asked to focus on the implementation for the default sounds) are `SoundRichDragListener`, `SoundKeyboardDragListener`, and `SoundDragListener`.  True?
2. I started looking at `SoundRichDragListener`, and I can see that the approach for sounds is significantly different from the examples that I [described how to find above](https://github.com/phetsims/scenery-phet/issues/849#issuecomment-2021545791).  You're passing wrapped audio buffers and the options for both creating and adding `SoundClip` instances for the grab and release sounds.  This makes for a somewhat 'wider' API than is used in, say, `AccordionBox`, where `TSoundPlayer`s are provided for the expand and collapse sounds.  Also, this approach means that a unique instance of the `SoundClip` will be created for each instance of `SoundRichDragListener`.  And finally, it's just a different API than is used elsewhere for default sounds.  Just to be clear, I'm not saying it's incorrect - it seems perfectly viable - it's just a break from precedent.  Was there a reason for doing it differently?

**Comment by jessegreenberg** [comment]
For 1 - Yes, that is correct.

For 2 - We recently changed this to be done as you describe in https://github.com/phetsims/scenery-phet/issues/889. The listeners now take TSoundPlayers (like AccordionBox) so they can be reused and also to fix issues like https://github.com/phetsims/equality-explorer/issues/215.

I think this has become stale after #889, but would you like to review anything else @jbphet?

**Comment by jbphet** [comment]
@jessegreenberg said:

> [W]ould you like to review anything else @jbphet?

I just looked over the new code, and it looks quite good.  I think this can be safely closed.
