### ISSUE TITLE
MixedFractionNode Memory Leak

### ISSUE THREAD

**Issue by marlitas** [phetsims/scenery-phet#857]
While memory testing `mean-share-and-balance` I found a memory leak and found MixedFractionNode to be a culprit. It looked like `MixedFractionNode` was holding onto layout Properties.

<img width="399" alt="image" src="https://github.com/phetsims/scenery-phet/assets/42476338/f1aa6e39-d196-4df3-8109-c2a0a95d1fb1">

I tried explicitly removing the MixedFractionNode as a child from the GridBox it was in, but that did not solve the problem either.

We found a workaround for `mean-share-and-balance` so there's not urgency for that sim, but may want to be looked at for future usage.

**Comment by marlitas** [comment]
This issue documents the original exploration in MSAB. https://github.com/phetsims/mean-share-and-balance/issues/261

**Comment by jonathanolson** [comment]
I checked briefly, and I see two fairly explicit potential memory leaks in MeanCalculationPanel involving MixedFractionNode.

Creation of unreducedFraction MixedFractionNode (with visibleProperty)
https://github.com/phetsims/mean-share-and-balance/blob/861bb092f522156273f1b7ebed2506be6a5c59e2/js/common/view/MeanCalculationPanel.ts#L191-L198

and valueRepresentation MixedFractionNode (with visibleProperty)
https://github.com/phetsims/mean-share-and-balance/blob/861bb092f522156273f1b7ebed2506be6a5c59e2/js/common/view/MeanCalculationPanel.ts#L229-L238

Both of these cases are passing in `visibleProperty: calculationsVisibleProperty` (thus will link to it - i.e. your calculationsVisibleProperty references a listener that references the MixedFractionNode). There appears to be no matching disposal of the MixedFractionNodes (which would release the listeners to the calculationVisibleProperty).

In the Multilink.multilinkAny in MeanCalculationPanel, I'm actually counting the memory leak of 7 different Nodes like this (the Texts will also need to be disposed).

Potentially restructuring so the multilink listens to the visibility property (and modifies the construction) could make it so that the tracking/disposal isn't needed. There might be other ways.

**Comment by marlitas** [comment]
Jonathan is so correct. Look at me trying to point fingers without knowing what I'm talking about. The above helped resolve memory leak questions. I think this is ready to close. Thanks for guiding me in the right direction @jonathanolson!
