### ISSUE TITLE
Reusable 'off scale' indicator Node

### ISSUE THREAD

**Issue by jessegreenberg** [phetsims/scenery-phet#893]
I was asked to add this indicator to trig-tour, from the number line sims.

![393004706-e0727170-c972-47d6-b0c2-211aab7163c5_360](https://github.com/user-attachments/assets/e9413cd0-2a75-4a26-8a0c-badd164362f5)

Ill add it to common code so that the code, translatable string, and eventually accessibility for it is reused.

From https://github.com/phetsims/trig-tour/issues/101.

**Comment by jessegreenberg** [comment]
@jbphet can you please review this? Assigning to you because you are responsible dev in the number line sims, but feel free to reassign if you don't have time at the moment.

I created `OffScaleIndicatorNode` and `demoOffScaleIndicatorNode` to show some of the options.

**Comment by jessegreenberg** [comment]
Adding blocks publication label because this added a string to scenery-phet and my understanding is that once SHAs are taken from main for any sim, that key can never be changed.

**Comment by jbphet** [comment]
Yes, it's okay with me if you integrate it into the Number Line Suite.  Keep in mind that you'll also need to move the translations of this string though, and then republish the updated sims so that we don't get more translations.  That may be more that you bargained for.  If so, it would also be okay with me to add documentation to the Number Line sims where this component is used stating that a common component now exists that can be used if a major refactoring ever occurs.

Also, you could potentially copy over all the existing translations.  I have some scripts to support this process (I think), but I'd probably need to help you with it since there isn't much documentation on how to do it.  Or you could just let translators do it again for this component.  I'll leave that to you and your team to figure out.

Let me know if you'd like to discuss this more and, if so, let's set up a meeting.

**Comment by jessegreenberg** [comment]
Thank you for reviewing. Sounds good. I decided to use the new `OffScaleIndicatorNode` in number-line-common, but keep using the same string from `NumberLineCommonStrings` so we don't have to worry about republishing or resubmitting translations. I added a comment pointing to this issue.

Closing.
